/* ============================================================
   ELECTRONOVA - Products & Categories Data
   ============================================================ */

const CATEGORIES = [
  { id: 'electromenager', name: 'Électroménager', icon: '🏠', color: '#dbeafe', count: 48, sub: ['Réfrigérateurs', 'Machines à laver', 'Lave-vaisselle', 'Fours & Cuisinières', 'Climatiseurs', 'Aspirateurs'] },
  { id: 'electronique', name: 'Électronique', icon: '📱', color: '#e0e7ff', count: 63, sub: ['Téléviseurs', 'Smartphones', 'Laptops & PC', 'Tablettes', 'Appareils photo', 'Consoles'] },
  { id: 'cuisine', name: 'Ustensiles Cuisine', icon: '🍳', color: '#fef9c3', count: 35, sub: ['Robots culinaires', 'Cafetières', 'Blenders', 'Grille-pain', 'Micro-ondes', 'Friteuses'] },
  { id: 'audio', name: 'Audio & Son', icon: '🎧', color: '#fce7f3', count: 42, sub: ['Casques audio', 'Enceintes', 'Barres de son', 'Écouteurs', 'Amplis Hi-Fi'] },
  { id: 'smart-home', name: 'Maison Connectée', icon: '💡', color: '#d1fae5', count: 27, sub: ['Éclairage LED', 'Sonnettes vidéo', 'Thermostats', 'Sécurité', 'Assistants vocaux'] },
  { id: 'accessoires', name: 'Accessoires Tech', icon: '🔌', color: '#ffedd5', count: 89, sub: ['Chargeurs', 'Câbles', 'Supports', 'Coques', 'Clés USB & stockage'] },
];

const BRANDS = ['Samsung', 'Apple', 'Sony', 'LG', 'Philips', 'Bosch', 'Dyson', 'Bose', 'Tefal', 'Xiaomi'];

const PRODUCTS = [
  {
    id: 1,
    name: 'Samsung Neo QLED 65" 4K Smart TV',
    brand: 'Samsung',
    category: 'electronique',
    subcategory: 'televisions',
    price: 1299.99,
    originalPrice: 1799.99,
    discount: 28,
    rating: 4.8,
    reviews: 234,
    stock: 8,
    sold: 312,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: './images/A1.png',
    images: ['./images/A1.png'],
    description: 'Vivez une expérience visuelle exceptionnelle avec cette Smart TV Neo QLED 4K Samsung. Technologie Quantum Mini LED pour des noirs profonds et des contrastes saisissants.',
    specs: { Résolution: '4K Ultra HD 3840x2160', Technologie: 'Neo QLED', Taille: '65 pouces', Processeur: 'Neural Quantum 4K', HDR: 'HDR10+', 'Fréquence': '120Hz', 'Smart TV': 'Tizen OS', Ports: '4x HDMI, 3x USB' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max 256Go',
    brand: 'Apple',
    category: 'electronique',
    subcategory: 'smartphones',
    price: 1329.00,
    originalPrice: 1329.00,
    discount: 0,
    rating: 4.9,
    reviews: 567,
    stock: 15,
    sold: 892,
    badge: 'popular',
    isNew: true,
    isFeatured: true,
    isPopular: true,
    image: './images/A2.png',
    images: ['./images/A2.png'],
    description: 'Le iPhone 15 Pro Max redéfinit les standards avec sa puce A17 Pro, son écran Super Retina XDR 6.7" et son système de caméra de 48MP.',
    specs: { Écran: '6.7" Super Retina XDR', Processeur: 'A17 Pro', Stockage: '256 Go', RAM: '8 Go', Caméra: '48 MP + 12 MP + 12 MP', 'Caméra Frontale': '12 MP TrueDepth', Batterie: '4422 mAh', OS: 'iOS 17' },
    colors: ['#8B7355', '#1a1a1a', '#4a4a4a', '#C8C3BC'],
  },
  {
    id: 3,
    name: 'Sony WH-1000XM5 Casque Bluetooth',
    brand: 'Sony',
    category: 'audio',
    subcategory: 'casques',
    price: 279.99,
    originalPrice: 349.99,
    discount: 20,
    rating: 4.9,
    reviews: 1204,
    stock: 22,
    sold: 1540,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: './images/A3.png',
    images: ['./images/A3.png'],
    description: 'La référence en matière de réduction de bruit active. Le WH-1000XM5 offre une qualité sonore HD et une autonomie de 30 heures.',
    specs: { Type: 'Over-Ear', Connexion: 'Bluetooth 5.2', 'Réduction de bruit': 'ANC avancé', Autonomie: '30h (ANC activé)', Recharge: 'USB-C, 3h recharge complète', Codec: 'LDAC, SBC, AAC', Micro: '8 microphones', Poids: '250g' },
    colors: ['#1a1a1a', '#c9b49a'],
  },
  {
    id: 4,
    name: 'MacBook Air M3 15" 8Go/256Go',
    brand: 'Apple',
    category: 'electronique',
    subcategory: 'laptops',
    price: 1299.00,
    originalPrice: 1299.00,
    discount: 0,
    rating: 4.8,
    reviews: 389,
    stock: 10,
    sold: 456,
    badge: 'new',
    isNew: true,
    isFeatured: true,
    isPopular: false,
    image: './images/A4.png',
    images: ['./images/A4.png'],
    description: 'Le MacBook Air M3 15" est le laptop ultime pour la productivité et la création. Léger, puissant et avec une autonomie exceptionnelle.',
    specs: { Écran: '15.3" Liquid Retina 2560x1664', Processeur: 'Apple M3 8-Core', RAM: '8 Go unifiée', Stockage: '256 Go SSD', GPU: '10-Core GPU', Batterie: 'Jusqu\'à 18h', Ports: '2x Thunderbolt 4, MagSafe 3', Poids: '1.51 kg' },
    colors: ['#c0c0c0', '#4a4a4a', '#d4a483', '#e8e4e0'],
  },
  {
    id: 5,
    name: 'LG Side-by-Side 668L Réfrigérateur',
    brand: 'LG',
    category: 'electromenager',
    subcategory: 'refrigerateurs',
    price: 899.99,
    originalPrice: 1199.99,
    discount: 25,
    rating: 4.6,
    reviews: 156,
    stock: 5,
    sold: 203,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A5.png',
    images: ['./images/A5.png'],
    description: 'Le réfrigérateur LG Side-by-Side offre un espace généreux de 668L avec technologie InstaView et distributeur d\'eau intégré.',
    specs: { Capacité: '668 L (Frigo 441L + Congél 227L)', Classe: 'A++', Technologie: 'InstaView Door-in-Door', Couleur: 'Inox platinum', Dimensions: 'H 179x L 91.3x P 73.5 cm', Garantie: '2 ans', 'Niveau sonore': '39 dB', Connexion: 'Wi-Fi ThinQ' },
    colors: ['#c0c0c0', '#1a1a1a'],
  },
  {
    id: 6,
    name: 'Dyson V15 Detect Absolute Aspirateur',
    brand: 'Dyson',
    category: 'electromenager',
    subcategory: 'aspirateurs',
    price: 649.99,
    originalPrice: 749.99,
    discount: 13,
    rating: 4.8,
    reviews: 445,
    stock: 18,
    sold: 678,
    badge: 'popular',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: './images/A6.png',
    images: ['./images/A6.png'],
    description: 'L\'aspirateur balai le plus avancé de Dyson. Laser détectant les particules invisibles et écran LCD affichant en temps réel la quantité de poussière aspirée.',
    specs: { Type: 'Aspirateur balai sans fil', Puissance: '240 AW', Autonomie: 'Jusqu\'à 60 min', Filtration: 'HEPA 5 couches', Capacité: '0.77 L', Poids: '3.1 kg', Technologie: 'Laser Detect', Niveaux: '3 modes d\'aspiration' },
    colors: ['#6366f1', '#f59e0b'],
  },
  {
    id: 7,
    name: 'Bose SoundLink Max Enceinte Portable',
    brand: 'Bose',
    category: 'audio',
    subcategory: 'enceintes',
    price: 379.99,
    originalPrice: 449.99,
    discount: 16,
    rating: 4.7,
    reviews: 298,
    stock: 30,
    sold: 512,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A7.png',
    images: ['./images/A7.png'],
    description: 'L\'enceinte portable Bose SoundLink Max délivre un son puissant et immersif avec 20h d\'autonomie et une résistance IP67.',
    specs: { Autonomie: '20 heures', Résistance: 'IP67 (eau et poussière)', Bluetooth: '5.3', Recharge: 'USB-C', Dimensions: '23.6 x 9.8 x 9 cm', Poids: '1.17 kg', Couleurs: '3 coloris disponibles', Micro: 'Mains libres intégré' },
    colors: ['#1a1a1a', '#8B7355', '#d1fae5'],
  },
  {
    id: 8,
    name: 'Samsung Galaxy Tab S9 Ultra 12.4"',
    brand: 'Samsung',
    category: 'electronique',
    subcategory: 'tablettes',
    price: 1099.00,
    originalPrice: 1249.00,
    discount: 12,
    rating: 4.7,
    reviews: 178,
    stock: 12,
    sold: 267,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A8.png',
    images: ['./images/A8.png'],
    description: 'La tablette Android la plus puissante. Écran Dynamic AMOLED 2X de 12.4" avec S Pen inclus pour la productivité et la créativité.',
    specs: { Écran: '12.4" Dynamic AMOLED 2X', Résolution: '2960x1848', Processeur: 'Snapdragon 8 Gen 2', RAM: '12 Go', Stockage: '256 Go', S: 'Pen S Pen inclus', Batterie: '11200 mAh', OS: 'Android 13' },
    colors: ['#1a1a1a', '#E8E4E0'],
  },
  {
    id: 9,
    name: 'De\'Longhi ECAM650.85 Cafetière Auto',
    brand: "De'Longhi",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 799.99,
    originalPrice: 999.99,
    discount: 20,
    rating: 4.6,
    reviews: 312,
    stock: 7,
    sold: 445,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A9.png',
    images: ['./images/A9.png'],
    description: 'Machine à café automatique haut de gamme avec broyeur intégré, écran tactile couleur et système LatteCrema pour des cappuccinos parfaits.',
    specs: { Type: 'Machine expresso automatique', Pression: '19 bars', Capacité: '2L eau / 400g café', Broyeur: 'Grain intégré', Écran: 'Tactile couleur 3.5"', Chaleur: 'Double chauffe-eau', Programmes: '12 boissons', Garantie: '2 ans' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 10,
    name: 'Bosch WAX32M81FR Lave-linge 9kg',
    brand: 'Bosch',
    category: 'electromenager',
    subcategory: 'lave-linge',
    price: 549.99,
    originalPrice: 699.99,
    discount: 21,
    rating: 4.5,
    reviews: 234,
    stock: 6,
    sold: 389,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/A10.png',
    images: ['./images/A10.png'],
    description: 'Lave-linge frontal Bosch Serie 8 avec moteur EcoSilence Drive, programme i-DOS et technologie ActiveWater Plus.',
    specs: { Capacité: '9 kg', Essorage: '1600 tr/min', Classe: 'A', Programmes: '28 programmes', Technologie: 'i-DOS + ActiveWater Plus', 'Niveau sonore': '48 dB', Connexion: 'Home Connect Wi-Fi', Garantie: '5 ans moteur' },
    colors: ['#ffffff', '#c0c0c0'],
  },
  {
    id: 11,
    name: 'Philips Hue White & Ambiante Kit',
    brand: 'Philips',
    category: 'smart-home',
    subcategory: 'eclairage',
    price: 129.99,
    originalPrice: 159.99,
    discount: 19,
    rating: 4.6,
    reviews: 543,
    stock: 45,
    sold: 1234,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A11.png',
    images: ['./images/A11.png'],
    description: 'Transformez votre intérieur avec l\'éclairage intelligent Philips Hue. Contrôlez 16 millions de couleurs depuis votre smartphone.',
    specs: { Contenu: '3 ampoules E27 + Pont Hue', Couleurs: '16 millions', Compatibilité: 'Alexa, Google Home, Apple HomeKit', Connexion: 'Zigbee via pont Hue', Durée: '25000 heures', Puissance: '9W équivalent 60W', Télécommande: 'App Hue', Protocole: 'Bluetooth + Zigbee' },
    colors: ['#ffffff', '#fbbf24', '#60a5fa', '#f472b6'],
  },
  {
    id: 12,
    name: 'Sony Alpha A7 IV Boîtier',
    brand: 'Sony',
    category: 'electronique',
    subcategory: 'cameras',
    price: 2499.00,
    originalPrice: 2799.00,
    discount: 11,
    rating: 4.9,
    reviews: 156,
    stock: 4,
    sold: 234,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/A12.png',
    images: ['./images/A12.png'],
    description: 'Hybride plein format polyvalent de Sony avec capteur BSI CMOS 33 MP, AF en temps réel et vidéo 4K 60p. Pour professionnels et passionnés.',
    specs: { Capteur: 'Full Frame BSI CMOS 33 MP', Processeur: 'BIONZ XR', AF: '759 points de détection de phase', Vidéo: '4K 60p, 4K 120p en recadrage', Stabilisation: '5 axes intégré', Écran: 'LCD tilting 3"', ISO: '50-204800 étendu', Tropicalisé: 'Oui (joints étanches)' },
    colors: ['#1a1a1a'],
  },
  {
    id: 13,
    name: 'Tefal ActiFry Genius XL Friteuse',
    brand: 'Tefal',
    category: 'cuisine',
    subcategory: 'friteuses',
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.5,
    reviews: 678,
    stock: 25,
    sold: 890,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A13.png',
    images: ['./images/A13.png'],
    description: 'Friteuse à air chaud Tefal ActiFry Genius XL pour 1.7 kg de frites avec seulement une cuillère d\'huile. 9 programmes automatiques.',
    specs: { Capacité: '1.7 kg', Technologie: 'Air chaud + palette rotative', Programmes: '9 programmes auto', Puissance: '1550W', Cuve: 'Amovible et lavable lave-vaisselle', Huile: '1 cuillère à café', Dimensions: '36.6x30x27.4 cm', Garantie: '2 ans' },
    colors: ['#ffffff', '#1a1a1a'],
  },
  {
    id: 14,
    name: 'Xiaomi Robot Aspirateur S20+',
    brand: 'Xiaomi',
    category: 'electromenager',
    subcategory: 'aspirateurs',
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    rating: 4.4,
    reviews: 445,
    stock: 20,
    sold: 678,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A14.png',
    images: ['./images/A14.png'],
    description: 'Robot aspirateur intelligent avec navigation laser, puissance d\'aspiration 6000 Pa et station de vidange automatique.',
    specs: { Aspiration: '6000 Pa', Navigation: 'LDS Laser', Batterie: '5200 mAh (200 min)', Station: 'Vidange automatique 2.5L', Cartographie: 'Multi-niveaux', Hauteur: '9.65 cm (sous meubles)', App: 'Mi Home / Xiaomi Home', Filtration: 'HEPA' },
    colors: ['#ffffff', '#1a1a1a'],
  },
  {
    id: 15,
    name: 'Apple AirPods Pro 2e génération',
    brand: 'Apple',
    category: 'audio',
    subcategory: 'ecouteurs',
    price: 249.00,
    originalPrice: 279.00,
    discount: 11,
    rating: 4.8,
    reviews: 892,
    stock: 35,
    sold: 1567,
    badge: 'popular',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: './images/A15.png',
    images: ['./images/A15.png'],
    description: 'Les AirPods Pro 2 redéfinissent l\'audio avec une réduction active de bruit 2x plus efficace, l\'audio spatial adaptatif et la puce H2.',
    specs: { Puce: 'Apple H2', ANC: 'Réduction de bruit active 2x améliorée', Autonomie: '6h (ANC) + 24h boîtier', Recharge: 'Lightning / MagSafe / Qi2', Résistance: 'IPX4 (écouteurs + boîtier)', 'Audio Spatial': 'Adaptatif avec suivi de tête', Capteurs: 'Accéléromètre + gyroscope', Contrôle: 'Tactile + Force Sensor' },
    colors: ['#ffffff'],
  },
  {
    id: 16,
    name: 'KitchenAid Artisan Robot Pâtissier 4.8L',
    brand: 'KitchenAid',
    category: 'cuisine',
    subcategory: 'robots',
    price: 499.99,
    originalPrice: 599.99,
    discount: 17,
    rating: 4.8,
    reviews: 567,
    stock: 9,
    sold: 890,
    badge: 'popular',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: './images/A16.png',
    images: ['./images/A16.png'],
    description: 'Le robot pâtissier iconique KitchenAid Artisan avec bol en acier inoxydable 4.8L, 10 vitesses et système d\'entraînement direct.',
    specs: { Capacité: '4.8 L', Puissance: '300W', Vitesses: '10 vitesses + impulsion', Accessoires: 'Fouet, crochet, feuille', Bol: 'Inox 4.8L', Système: 'Entraînement direct planétaire', Couleurs: '20+ coloris', Garantie: '5 ans' },
    colors: ['#ef4444', '#1a1a1a', '#c0c0c0', '#fbbf24', '#3b82f6'],
  },
  {
    id: 17,
    name: 'LG OLED Evo G3 55" 4K Dolby Vision',
    brand: 'LG',
    category: 'electronique',
    subcategory: 'televisions',
    price: 1599.99,
    originalPrice: 2199.99,
    discount: 27,
    rating: 4.9,
    reviews: 167,
    stock: 5,
    sold: 234,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: false,
    image: './images/A17.png',
    images: ['./images/A17.png'],
    description: 'L\'excellence OLED avec les panneaux EVO de LG pour des noirs absolus, des couleurs parfaites et un temps de réponse de 0.1ms.',
    specs: { Technologie: 'OLED EVO G3', Résolution: '4K Ultra HD', Taille: '55"', HDR: 'Dolby Vision IQ + HDR10 Pro', Fréquence: '120Hz', Processeur: 'α9 Gen 6 AI', 'Smart TV': 'webOS 23', Gaming: 'HDMI 2.1, FreeSync Premium Pro, G-Sync Compatible' },
    colors: ['#1a1a1a'],
  },
  {
    id: 18,
    name: 'Nespresso Vertuo Next Premium',
    brand: 'Nespresso',
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 119.99,
    originalPrice: 169.99,
    discount: 29,
    rating: 4.5,
    reviews: 789,
    stock: 40,
    sold: 1234,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A18.png',
    images: ['./images/A18.png'],
    description: 'Machine Nespresso Vertuo avec technologie Centrifusion pour extraire le meilleur de chaque capsule. 5 tailles de café au programme.',
    specs: { Technologie: 'Centrifusion', Tailles: '5 (Espresso à Alto)', Capacité: '1.1 L', Chauffe: '30 secondes', Pression: '19 bars', Bac: '8 capsules usagées', Connexion: 'Bluetooth pour mises à jour', Couleur: 'Noir / Chromé' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 19,
    name: 'Samsung Galaxy Watch 6 Classic 47mm',
    brand: 'Samsung',
    category: 'accessoires',
    subcategory: 'montres',
    price: 349.99,
    originalPrice: 429.99,
    discount: 19,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A19.png',
    images: ['./images/A19.png'],
    description: 'La Galaxy Watch 6 Classic avec lunette tournante physique, suivi santé avancé et autonomie de 40 heures.',
    specs: { Taille: '47mm', Écran: 'Super AMOLED 1.5" 480x480', OS: 'Wear OS 4 + One UI Watch 5', Processeur: 'Exynos W930', RAM: '2 Go', Stockage: '16 Go', Batterie: '425 mAh (40h)', Capteurs: 'ECG, BIA, SpO2, FC, Pression artérielle' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 20,
    name: 'Vitamix 5200 Blender Professionnel',
    brand: 'Vitamix',
    category: 'cuisine',
    subcategory: 'blenders',
    price: 449.99,
    originalPrice: 549.99,
    discount: 18,
    rating: 4.9,
    reviews: 234,
    stock: 12,
    sold: 345,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/A20.png',
    images: ['./images/A20.png'],
    description: 'Le blender professionnel Vitamix 5200 pour smoothies parfaits, soupes chaudes et bien plus. Moteur 2HP ultra-puissant.',
    specs: { Moteur: '2 HP (1.49 kW)', Vitesses: 'Variable 10 vitesses', Lames: 'Inox aiguisées laser 9cm', Bol: '2.1 L Tritan BPA Free', Chauffage: 'Friction (soupes chaudes)', Programmes: 'Manuel + 3 auto sur Pro', Garantie: '7 ans', Poids: '5.2 kg' },
    colors: ['#1a1a1a', '#ffffff', '#ef4444'],
  },
  {
    id: 21,
    name: 'Dell XPS 15 i7 32Go RTX 4070',
    brand: 'Dell',
    category: 'electronique',
    subcategory: 'laptops',
    price: 1899.99,
    originalPrice: 2299.99,
    discount: 17,
    rating: 4.7,
    reviews: 198,
    stock: 6,
    sold: 312,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: false,
    image: './images/A21.png',
    images: ['./images/A21.png'],
    description: 'Le Dell XPS 15 avec processeur Intel Core i7-13700H, GPU RTX 4070 et écran OLED 3.5K pour les créatifs et gamers exigeants.',
    specs: { Processeur: 'Intel Core i7-13700H', GPU: 'NVIDIA RTX 4070 8Go', RAM: '32 Go DDR5', Stockage: '1 To NVMe SSD', Écran: '15.6" OLED 3456x2160', Batterie: '86 Wh (13h)', Ports: '2x TB4, USB-A, SD, HDMI 2.1', Poids: '1.86 kg' },
    colors: ['#c0c0c0', '#1a1a1a'],
  },
  {
    id: 22,
    name: 'Anker PowerCore 26800 mAh',
    brand: 'Anker',
    category: 'accessoires',
    subcategory: 'chargeurs',
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    rating: 4.7,
    reviews: 1234,
    stock: 60,
    sold: 3456,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A22.png',
    images: ['./images/A22.png'],
    description: 'Batterie externe ultra-capacité Anker 26800 mAh avec charge rapide PowerIQ et 3 ports USB pour recharger jusqu\'à 3 appareils simultanément.',
    specs: { Capacité: '26800 mAh', Sorties: '3x USB-A + 1x USB-C', Charge: 'PowerIQ 3.0 + USB-C 45W', Entrée: 'Micro USB + USB-C', Temps: '6.5h recharge complète', Poids: '490g', Certifications: 'CE, FCC, RoHS', Garantie: '18 mois' },
    colors: ['#1a1a1a', '#3b82f6'],
  },
  {
    id: 23,
    name: 'Philips 3000 Purificateur d\'Air',
    brand: 'Philips',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 199.99,
    originalPrice: 279.99,
    discount: 29,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: false,
    image: './images/A23.png',
    images: ['./images/A23.png'],
    description: 'Purificateur d\'air Philips Series 3000i avec filtre HEPA NanoProtect et capteurs intelligents pour une qualité de l\'air optimale.',
    specs: { Surface: 'Jusqu\'à 130 m²', Filtration: 'HEPA Grade H13 + Charbon actif', CADR: '333 m³/h', Capteurs: 'PM2.5, COV, Humidité, Température', Connectivité: 'Wi-Fi + App Clean Home+', Bruit: '19 dB (mode nuit)', Consommation: 'Max 60W', Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 24,
    name: 'GoPro HERO12 Black Action Camera',
    brand: 'GoPro',
    category: 'electronique',
    subcategory: 'cameras',
    price: 349.99,
    originalPrice: 449.99,
    discount: 22,
    rating: 4.7,
    reviews: 445,
    stock: 18,
    sold: 678,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A24.png',
    images: ['./images/A24.png'],
    description: 'La GoPro HERO12 Black capture des vidéos 5.3K ultra fluides avec stabilisation HyperSmooth 6.0 et une autonomie améliorée de 70%.',
    specs: { Vidéo: '5.3K 60fps / 4K 120fps', Photo: '27 MP', Stabilisation: 'HyperSmooth 6.0', Étanchéité: '10m sans boîtier', Batterie: '1720 mAh (+70% vs HERO11)', Écran: 'Avant 2.27" + Arrière 1.4"', HDR: 'Photo et vidéo HDR', Connexion: 'Wi-Fi + Bluetooth + GPS' },
    colors: ['#1a1a1a'],
  },
  {
    id: 25,
    name: 'Roborock S8 Pro Ultra Robot Aspirateur',
    brand: 'Roborock',
    category: 'electromenager',
    subcategory: 'aspirateurs',
    price: 1199.99,
    originalPrice: 1499.99,
    discount: 20,
    rating: 4.8,
    reviews: 178,
    stock: 8,
    sold: 234,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: false,
    image: './images/A25.png',
    images: ['./images/A25.png'],
    description: 'Le robot aspirateur-laveur Roborock S8 Pro Ultra avec station tout-en-un : vidange automatique, remplissage d\'eau et lavage de la serpillière.',
    specs: { Aspiration: '6000 Pa', Navigation: 'LiDAR 3D + caméra RGB', Station: 'Vidange + Remplissage + Lavage serpillière', Brosse: 'DuoRoller Pro', Serpillière: 'Sonic Vibration 3000 vibr/min', Batterie: '5200 mAh (180 min)', App: 'Roborock / Alexa / Google', Filtre: 'HEPA E11' },
    colors: ['#1a1a1a', '#ffffff'],
  },
  {
    id: 26,
    name: 'corsair headset',
    brand: 'Corsair',
    category: 'audio',
    subcategory: 'enceintes',
    price: 113.04,
    originalPrice: 132.99,
    discount: 15,
    rating: 4.7,
    reviews: 298,
    stock: 20,
    sold: 512,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/corsair headset.png',
    images: ['./images/corsair headset.png'],
    description: 'Elle est conçus pour offrir pour offrir une expérience audio exceptionnelle avec des fonctionnalités avancées de personnalisation audio et une compatibilité multi-plateforme.',
    specs: { Autonomie: '70 heures', Résistance: 'Robuste comme l\'aluminiun et le plastique ABS', Bluetooth: '2.5 GHZ', Recharge: 'USB-C', Dimensions: '105 x 170.5 x 193 cm', Poids: '330 kg', Couleurs: '3 coloris disponibles', Micro: 'NVIDIA Broadcast' },
    colors: ['#1a1a1a', '#8B7355', '#f8f8f8'],
  },
  {
    id: 27,
    name: 'razer speaker',
    brand: 'Razer',
    category: 'audio',
    subcategory: 'enceintes',
    price: 288.00,
    originalPrice: 320.00,
    discount: 10,
    rating: 4.7,
    reviews: 298,
    stock: 20,
    sold: 512,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A27.png',
    images: ['./images/A27.png'],
    description: 'Les haut-parleurs Razer sont conçus pour offrir une expérience audio immersive avec un son surround 7.1 et une qualité sonore exceptionnelle.',
    specs: { Autonomie: '17 heures', Résistance: 'Imperméable', Bluetooth: '20KHZ', Recharge: 'USB-C', Dimensions: '26 x 18 x 18.3 cm', Poids: '1.17 kg', Couleurs: '3 coloris disponibles', Micro: 'Mains libres intégré' },
    colors: ['#1a1a1a', '#8B7355', '#d1fae5'],
  },
  {
    id: 28,
    name: 'asus mic',
    brand: 'Asus',
    category: 'audio',
    subcategory: 'enceintes',
    price: 288.00,
    originalPrice: 320.00,
    discount: 10,
    rating: 4.7,
    reviews: 298,
    stock: 20,
    sold: 512,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/A28.png',
    images: ['./images/A28.png'],
    description: 'Les haut-parleurs Razer sont conçus pour offrir une expérience audio immersive avec un son surround 7.1 et une qualité sonore exceptionnelle.',
    specs: { Autonomie: '17 heures', Résistance: 'Structure externe rigide résistant au manipulation', Bluetooth: '192KHZ', Recharge: 'USB-C', Dimensions: '170 x 200 x 293 cm', Poids: '633g', Couleurs: '3 coloris disponibles', Micro: 'Haute Qualité' },
    colors: ['#1a1a1a', '#8B7355', '#d1fae5'],
  },
  {
    id: 29,
    name: 'Echo Dot',
    brand: 'Echo',
    category: 'audio',
    subcategory: 'enceintes',
    price: 109.99,
    originalPrice: 129.99,
    discount: 15,
    rating: 4.7,
    reviews: 298,
    stock: 20,
    sold: 512,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/product_img2.png',
    images: ['./images/product_img2.png'],
    description: 'Elle intègre l\'assistant vocal Alexa pour contrôler la musique, poser des questions ou gérer des objets connectés.',
    specs: { Autonomie: 'Pas d\'autonomie', Résistance: 'Réservé exclusivement à un usage intérieur', Bluetooth: 'Profil A2DP et AVRCP', Recharge: 'USB-C', Dimensions: '100 x 100 x 89 mm', Poids: '340g', Couleurs: '3 coloris disponibles', Micro: 'Haute Qualité' },
    colors: ['#1a1a1a', '#8B7355', '#d1fae5'],
  },
  {
    id: 30,
    name: 'Boat Stone',
    brand: 'Boat',
    category: 'audio',
    subcategory: 'enceintes',
    price: 110.99,
    originalPrice: 124.30,
    discount: 12,
    rating: 4.7,
    reviews: 298,
    stock: 20,
    sold: 512,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/product_img5.png',
    images: ['./images/product_img5.png'],
    description: 'Elle intègre la technologie boAt Signature Sound qui délivre un son riche, net et équilibré.',
    specs: { Autonomie: '16 heures', Résistance: 'Résistante à l\'eau et à la poussière', Bluetooth: '5.0 à 5.4', Recharge: 'USB-C', Dimensions: '30 x 15 cm', Poids: '2.1 kg', Couleurs: '3 coloris disponibles', Micro: 'Haute Qualité' },
    colors: ['#1a1a1a', '#8B7355', '#d1fae5'],
  },
  {
    id: 31,
    name: 'Apple Watch SE',
    brand: 'Apple',
    category: 'accessoires',
    subcategory: 'montres',
    price: 293.99,
    originalPrice: 349.99,
    discount: 15,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/product_img3.png',
    images: ['./images/product_img3.png'],
    description: 'Elle est une montre connectée polyvalente qui regroupe les fonctionnalités essentielles de suivi de la santé, du sport et de la sécurité d\'Apple.',
    specs: { Taille: '47mm', Écran: 'Écran Retina OLED LTPO', OS: 'watchOS 10', Processeur: 'S8 SiP', RAM: '1 Go', Stockage: '32 Go', Batterie: 'lithium-ion (18h)', Capteurs: 'ECG, BIA, SpO2, FC, Pression artérielle' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 32,
    name: 'TP-Link Tapo C210',
    brand: 'TP-Link',
    category: 'accessoires',
    subcategory: 'montres',
    price: 39.90,
    originalPrice: 43.89,
    discount: 10,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/product_img6.png',
    images: ['./images/product_img6.png'],
    description: 'TP-Link Tapo C210 est une caméra de surveillance intérieure connectée et motorisée qui offre une définition 2K très nette et une vision à 360° pour sécuriser efficacement votre maison.',
    specs: { Résolution: '2K', Vision: '360°', Dimmensions: '6,6 x 85 x 117,7 mm', Connectivité: 'Wi-Fi(2.4/5GHz)', Microphone: 'Haut-Parleur intégré' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 33,
    name: 'Vidéoprojecteur Samsung Freestyl',
    brand: 'Vidéoprojecteur',
    category: 'accessoires',
    subcategory: 'montres',
    price: 528.65,
    originalPrice: 620.00,
    discount: 15,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'new',
    isNew: true,
    isFeatured: true,
    isPopular: false,
    image: './images/product_img16.png',
    images: ['./images/product_img16.png'],
    description: 'Vidéoprojecteur Samsung Freestyl avec projection 4K et son surround.',
    specs: { Résolution: '4K', Vision: '360°', Dimmensions: '6,6 x 85 x 117,7 mm', Connectivité: 'Wi-Fi(2.4/5GHz)', Microphone: 'Haut-Parleur intégré' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 34,
    name: 'MEKO Stylet',
    brand: 'MEKO',
    category: 'accessoires',
    subcategory: 'montres',
    price: 13.99,
    originalPrice: 15.38,
    discount: 10,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/product_img7.png',
    images: ['./images/product_img7.png'],
    description: 'Stylet MEKO pour écrans tactiles.',
    specs: { Matière: 'Plastique', Longueur: '120mm', Diamètre: '8mm' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 35,
    name: 'SteelSeries QcK Edge',
    brand: 'SteelSeries',
    category: 'accessoires',
    subcategory: 'montres',
    price: 52.56,
    originalPrice: 62.00,
    discount: 15,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/steelseries l.png',
    images: ['./images/steelseries l.png'],
    description: 'SteelSeries QcK Edge avec surface de jeu rétroéclairée et réactivité ultra-rapide.',
    specs: { Dimensions: '450 x 300 x 1 mm', Poids: '350 g', Surface: 'Rétroéclairée', Rétroéclairage: 'RGB' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 36,
    name: 'Lampe',
    brand: 'Lampe',
    category: 'accessoires',
    subcategory: 'montres',
    price: 13.75,
    originalPrice: 15.28,
    discount: 10,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: './images/product_img1.png',
    images: ['./images/product_img1.png'],
    description: 'Lampe de bureau avec rétroéclairage RGB.',
    specs: { Dimensions: '20 x 20 x 30 cm', Poids: '1.5 kg', Rétroéclairage: 'RGB', Connectivité: 'USB-C' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
  id: 37,
  name: 'Samsung Galaxy S22 Ultra',
  brand: 'Samsung',
  category: 'electronique',
  subcategory: 'smartphones',
  price: 899.99,
  originalPrice: 1099.99,
  discount: 18,
  rating: 4.7,
  reviews: 456,
  stock: 15,
  sold: 678,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/Samsung galaxy s22.webp',
  images: ['./images/Samsung galaxy s22.webp'],
  description: 'Le Samsung Galaxy S22 Ultra avec écran Dynamic AMOLED 2X 6.8", caméra 108MP et S Pen intégré.',
  specs: { Écran: '6.8" Dynamic AMOLED 2X 3088x1440', Processeur: 'Snapdragon 8 Gen 1', RAM: '12 Go', Stockage: '256 Go', Caméra: '108 MP + 12 MP + 10 MP + 10 MP', Batterie: '5000 mAh', OS: 'Android 12' },
  colors: ['#1a1a1a', '#ffffff', '#d4a483'],
},
{
  id: 38,
  name: 'Samsung Galaxy S24 Ultra',
  brand: 'Samsung',
  category: 'electronique',
  subcategory: 'smartphones',
  price: 1299.99,
  originalPrice: 1499.99,
  discount: 13,
  rating: 4.8,
  reviews: 234,
  stock: 12,
  sold: 345,
  badge: 'new',
  isNew: true,
  isFeatured: true,
  isPopular: true,
  image: './images/s24.jpg',
  images: ['./images/s24.jpg'],
  description: 'Le Galaxy S24 Ultra avec intelligence IA Galaxy, écran Dynamic AMOLED 2X et caméra 200MP.',
  specs: { Écran: '6.8" Dynamic AMOLED 2X 3120x1440', Processeur: 'Snapdragon 8 Gen 3', RAM: '12 Go', Stockage: '512 Go', Caméra: '200 MP + 50 MP + 12 MP + 10 MP', Batterie: '5000 mAh', OS: 'Android 14' },
  colors: ['#1a1a1a', '#c0c0c0', '#d4a483', '#8B7355'],
},
{
  id: 39,
  name: 'Samsung Galaxy S25',
  brand: 'Samsung',
  category: 'electronique',
  subcategory: 'smartphones',
  price: 999.99,
  originalPrice: 1199.99,
  discount: 17,
  rating: 4.7,
  reviews: 123,
  stock: 18,
  sold: 234,
  badge: 'new',
  isNew: true,
  isFeatured: true,
  isPopular: false,
  image: './images/s25.png',
  images: ['./images/s25.png'],
  description: 'Le Galaxy S25 avec puce Snapdragon 8 Gen 4 et IA avancée pour une expérience smartphone ultime.',
  specs: { Écran: '6.2" Dynamic AMOLED 2X 2340x1080', Processeur: 'Snapdragon 8 Gen 4', RAM: '8 Go', Stockage: '256 Go', Caméra: '50 MP + 12 MP + 10 MP', Batterie: '4000 mAh', OS: 'Android 15' },
  colors: ['#1a1a1a', '#c0c0c0', '#3b82f6', '#f472b6'],
},
{
  id: 40,
  name: 'iPhone 15',
  brand: 'Apple',
  category: 'electronique',
  subcategory: 'smartphones',
  price: 799.00,
  originalPrice: 799.00,
  discount: 0,
  rating: 4.8,
  reviews: 567,
  stock: 25,
  sold: 890,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/ip15.jpg',
  images: ['./images/ip15.jpg'],
  description: 'L\'iPhone 15 avec puce A16 Bionic, écran Super Retina XDR 6.1" et Dynamic Island.',
  specs: { Écran: '6.1" Super Retina XDR 2556x1179', Processeur: 'A16 Bionic', Stockage: '128 Go', RAM: '6 Go', Caméra: '48 MP + 12 MP', 'Caméra Frontale': '12 MP', Batterie: '3349 mAh', OS: 'iOS 17' },
  colors: ['#1a1a1a', '#c0c0c0', '#4a90e2', '#f5a623', '#e91e63'],
},
{
  id: 41,
  name: 'iPhone 16 Pro',
  brand: 'Apple',
  category: 'electronique',
  subcategory: 'smartphones',
  price: 1199.00,
  originalPrice: 1199.00,
  discount: 0,
  rating: 4.9,
  reviews: 234,
  stock: 15,
  sold: 456,
  badge: 'new',
  isNew: true,
  isFeatured: true,
  isPopular: true,
  image: './images/ip16.png',
  images: ['./images/ip16.png'],
  description: 'L\'iPhone 16 Pro avec puce A18 Pro, écran Super Retina XDR 6.3" et bouton Action personnalisable.',
  specs: { Écran: '6.3" Super Retina XDR 2868x1320', Processeur: 'A18 Pro', Stockage: '256 Go', RAM: '8 Go', Caméra: '48 MP + 12 MP + 12 MP', 'Caméra Frontale': '12 MP', Batterie: '3582 mAh', OS: 'iOS 18' },
  colors: ['#8B7355', '#1a1a1a', '#c0c0c0', '#f5f5dc'],
},
{
  id: 42,
  name: 'Acer Predator X27 27" 4K 144Hz',
  brand: 'Acer',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 899.99,
  originalPrice: 1099.99,
  discount: 18,
  rating: 4.7,
  reviews: 189,
  stock: 8,
  sold: 234,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/acer monitor.jfif',
  images: ['./images/acer monitor.jfif'],
  description: 'Moniteur gaming Acer Predator X27 27" 4K UHD avec HDR 1000 et 144Hz pour les gamers exigeants.',
  specs: { Écran: '27" IPS 4K UHD 3840x2160', Fréquence: '144Hz', 'Temps de réponse': '4ms', HDR: 'HDR1000', 'NITS': '1000 nits', Couleurs: '99% Adobe RGB', Sync: 'Compatible', Ports: '2x HDMI, DisplayPort' },
  colors: ['#1a1a1a'],
},
{
  id: 43,
  name: 'Acer Nitro VG240 24" 144Hz',
  brand: 'Acer',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 199.99,
  originalPrice: 249.99,
  discount: 20,
  rating: 4.5,
  reviews: 345,
  stock: 20,
  sold: 567,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/acer budget monitor.jfif',
  images: ['./images/acer budget monitor.jfif'],
  description: 'Moniteur gaming Acer Nitro 24" Full HD 144Hz, idéal pour le gaming entrée de gamme.',
  specs: { Écran: '23.8" TN Full HD 1920x1080', Fréquence: '144Hz', 'Temps de réponse': '1ms', Couleurs: '72% NTSC', FreeSync: 'AMD FreeSync', Ports: '1x HDMI, 1x DisplayPort', Inclinaison: '-5° à 25°' },
  colors: ['#1a1a1a'],
},
{
  id: 44,
  name: 'ASUS TUF Gaming VG27AQ1A 27" 165Hz',
  brand: 'ASUS',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 349.99,
  originalPrice: 429.99,
  discount: 19,
  rating: 4.6,
  reviews: 234,
  stock: 15,
  sold: 345,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/asus_monitor.jpg',
  images: ['./images/asus_monitor.jpg'],
  description: 'Moniteur ASUS TUF Gaming 27" IPS 165Hz avec ELMB pour une expérience gaming fluide.',
  specs: { Écran: '27" IPS WQHD 2560x1440', Fréquence: '165Hz', 'Temps de réponse': '1ms (ELMB)', Couleurs: 'DCI-P3 95%', FreeSync: 'Premium Pro', Ports: '2x HDMI, DisplayPort', Ergonomie: 'Pivot, Inclinaison, Hauteur' },
  colors: ['#1a1a1a'],
},
{
  id: 45,
  name: 'Logitech G272 27" 165Hz',
  brand: 'Logitech',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 299.99,
  originalPrice: 349.99,
  discount: 14,
  rating: 4.5,
  reviews: 178,
  stock: 12,
  sold: 234,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/logi monitor.jpg',
  images: ['./images/logi monitor.jpg'],
  description: 'Moniteur gaming Logitech G272 27" Full HD 165Hz avec design ergonomique.',
  specs: { Écran: '27" IPS Full HD 1920x1080', Fréquence: '165Hz', 'Temps de réponse': '1ms', Couleurs: 'sRGB 99%', FreeSync: 'Compatible', Ports: '2x HDMI, DisplayPort', Ergonomie: 'Réglable en hauteur' },
  colors: ['#1a1a1a'],
},
{
  id: 46,
  name: 'MSI Optix G272Q 27" 165Hz',
  brand: 'MSI',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 279.99,
  originalPrice: 329.99,
  discount: 15,
  rating: 4.5,
  reviews: 156,
  stock: 18,
  sold: 234,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/msi monitor 2.jpg',
  images: ['./images/msi monitor 2.jpg'],
  description: 'Moniteur MSI Optix G272Q 27" QHD 165Hz avec frameless design pour gaming immersif.',
  specs: { Écran: '27" IPS QHD 2560x1440', Fréquence: '165Hz', 'Temps de réponse': '1ms', Couleurs: 'sRGB 110%', FreeSync: 'Premium', Ports: '2x HDMI, DisplayPort', AntiFlicker: 'Oui' },
  colors: ['#1a1a1a'],
},
{
  id: 47,
  name: 'Razer Raptor 27" 165Hz',
  brand: 'Razer',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 699.99,
  originalPrice: 799.99,
  discount: 13,
  rating: 4.7,
  reviews: 123,
  stock: 8,
  sold: 178,
  badge: 'promo',
  isNew: false,
  isFeatured: true,
  isPopular: false,
  image: './images/razer monitor.jpg',
  images: ['./images/razer monitor.jpg'],
  description: 'Moniteur gaming Razer Raptor 27" QHD 165Hz avec design Chroma RGB premium.',
  specs: { Écran: '27" IPS QHD 2560x1440', Fréquence: '165Hz', 'Temps de réponse': '1ms', Couleurs: '95% DCI-P3', GSync: 'Compatible', RGB: 'Chroma RGB', Ports: 'HDMI, DisplayPort, USB-C', Stand: 'Aluminium CNC' },
  colors: ['#1a1a1a', '#00ff00'],
},
{
  id: 48,
  name: 'ViewSonic Elite XG270QG 27" 165Hz',
  brand: 'ViewSonic',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 449.99,
  originalPrice: 549.99,
  discount: 18,
  rating: 4.6,
  reviews: 145,
  stock: 10,
  sold: 198,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/view monitor.png',
  images: ['./images/view monitor.png'],
  description: 'Moniteur ViewSonic Elite XG270QG 27" QHD 165Hz avec G-Sync pour gaming professionnel.',
  specs: { Écran: '27" IPS QHD 2560x1440', Fréquence: '165Hz', 'Temps de réponse': '1ms', Couleurs: '72% NTSC', GSync: 'Compatible', Ports: '2x HDMI, DisplayPort', Ergonomie: 'Pivot, Inclinaison, Hauteur' },
  colors: ['#1a1a1a'],
},
{
  id: 49,
  name: 'ViewSonic VX3276-2K-MHD 32" QHD',
  brand: 'ViewSonic',
  category: 'electronique',
  subcategory: 'moniteurs',
  price: 329.99,
  originalPrice: 399.99,
  discount: 18,
  rating: 4.5,
  reviews: 167,
  stock: 14,
  sold: 234,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/viewsonic monitor.png',
  images: ['./images/viewsonic monitor.png'],
  description: 'Moniteur ViewSonic 32" QHD avec design ultra-slim et frameless pour bureautique et multimédia.',
  specs: { Écran: '31.5" IPS QHD 2560x1440', Fréquence: '75Hz', 'Temps de réponse': '5ms', Couleurs: 'sRGB 100%', Ports: '2x HDMI, DisplayPort', Design: 'Ultra-slim 7mm', Inclinaison: '-5° à 20°' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
  id: 50,
  name: 'PC Gaming RTX 3060 Ti',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 1299.99,
  originalPrice: 1499.99,
  discount: 13,
  rating: 4.6,
  reviews: 89,
  stock: 5,
  sold: 123,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/3060 ti pc.jpg',
  images: ['./images/3060 ti pc.jpg'],
  description: 'PC gaming avec RTX 3060 Ti, Ryzen 5 5600X et 16Go RAM pour gaming 1080p/1440p.',
  specs: { Processeur: 'AMD Ryzen 5 5600X', GPU: 'NVIDIA RTX 3060 Ti 8Go', RAM: '16 Go DDR4 3200MHz', Stockage: '1 To NVMe SSD', Refroidissement: 'Liquid Cooling 240mm', Alimentation: '650W Gold', Boîtier: 'Glass Panel RGB' },
  colors: ['#1a1a1a', '#3b82f6'],
},
{
  id: 51,
  name: 'PC Gaming RTX 3070',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 1699.99,
  originalPrice: 1999.99,
  discount: 15,
  rating: 4.7,
  reviews: 67,
  stock: 4,
  sold: 89,
  badge: 'promo',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/3070 pc.jpg',
  images: ['./images/3070 pc.jpg'],
  description: 'PC gaming haute performance avec RTX 3070, Ryzen 7 5800X et 32Go RAM pour gaming 1440p.',
  specs: { Processeur: 'AMD Ryzen 7 5800X', GPU: 'NVIDIA RTX 3070 8Go', RAM: '32 Go DDR4 3600MHz', Stockage: '2 To NVMe SSD', Refroidissement: 'Liquid Cooling 360mm', Alimentation: '750W Gold', Boîtier: 'Full Tower RGB' },
  colors: ['#1a1a1a', '#ef4444'],
},
{
  id: 52,
  name: 'PC Gaming RTX 3080',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 2499.99,
  originalPrice: 2999.99,
  discount: 17,
  rating: 4.8,
  reviews: 45,
  stock: 3,
  sold: 67,
  badge: 'promo',
  isNew: false,
  isFeatured: true,
  isPopular: false,
  image: './images/3080 pc.jpg',
  images: ['./images/3080 pc.jpg'],
  description: 'PC gaming ultra-performance avec RTX 3080, Ryzen 9 5900X et 32Go RAM pour gaming 4K.',
  specs: { Processeur: 'AMD Ryzen 9 5900X', GPU: 'NVIDIA RTX 3080 10Go', RAM: '32 Go DDR4 3600MHz', Stockage: '2 To NVMe SSD + 2 To HDD', Refroidissement: 'Liquid Cooling 360mm', Alimentation: '850W Platinum', Boîtier: 'Premium Full Tower' },
  colors: ['#1a1a1a', '#f59e0b'],
},
{
  id: 53,
  name: 'PC Compact RTX 3050',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 899.99,
  originalPrice: 1099.99,
  discount: 18,
  rating: 4.5,
  reviews: 123,
  stock: 8,
  sold: 178,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/compact pc.png',
  images: ['./images/compact pc.png'],
  description: 'PC compact avec RTX 3050, Intel i5-12400 et 16Go RAM, format mini-ITX idéal pour petits espaces.',
  specs: { Processeur: 'Intel Core i5-12400', GPU: 'NVIDIA RTX 3050 8Go', RAM: '16 Go DDR4 3200MHz', Stockage: '512 Go NVMe SSD', Format: 'Mini-ITX', Refroidissement: 'Air Cooling', Alimentation: '500W Bronze' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
  id: 54,
  name: 'PC Gaming GTX 1050 Ti',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 699.99,
  originalPrice: 849.99,
  discount: 18,
  rating: 4.4,
  reviews: 156,
  stock: 10,
  sold: 234,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/pc-1050ti.png',
  images: ['./images/pc-1050ti.png'],
  description: 'PC gaming entrée de gamme avec GTX 1050 Ti, Ryzen 3 3200G et 8Go RAM pour gaming 1080p.',
  specs: { Processeur: 'AMD Ryzen 3 3200G', GPU: 'NVIDIA GTX 1050 Ti 4Go', RAM: '8 Go DDR4 2666MHz', Stockage: '512 Go SSD', Refroidissement: 'Air Cooling', Alimentation: '450W Bronze', Boîtier: 'Mid Tower' },
  colors: ['#1a1a1a'],
},
{
  id: 55,
  name: 'PC Gaming RTX 3050',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 799.99,
  originalPrice: 949.99,
  discount: 16,
  rating: 4.5,
  reviews: 134,
  stock: 12,
  sold: 189,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/pc-rtx3050.jpg',
  images: ['./images/pc-rtx3050.jpg'],
  description: 'PC gaming avec RTX 3050, Ryzen 5 5600G et 16Go RAM pour gaming 1080p optimisé.',
  specs: { Processeur: 'AMD Ryzen 5 5600G', GPU: 'NVIDIA RTX 3050 8Go', RAM: '16 Go DDR4 3200MHz', Stockage: '1 To NVMe SSD', Refroidissement: 'Air Cooling', Alimentation: '550W Bronze', Boîtier: 'Mid Tower RGB' },
  colors: ['#1a1a1a', '#3b82f6'],
},
{
  id: 56,
  name: 'PC Gaming RTX 3060',
  brand: 'Custom',
  category: 'electronique',
  subcategory: 'pc-gaming',
  price: 1099.99,
  originalPrice: 1299.99,
  discount: 15,
  rating: 4.6,
  reviews: 98,
  stock: 7,
  sold: 145,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/pc-rtx3060.jpg',
  images: ['./images/pc-rtx3060.jpg'],
  description: 'PC gaming avec RTX 3060, Ryzen 5 5600X et 16Go RAM pour gaming 1080p/1440p.',
  specs: { Processeur: 'AMD Ryzen 5 5600X', GPU: 'NVIDIA RTX 3060 12Go', RAM: '16 Go DDR4 3200MHz', Stockage: '1 To NVMe SSD', Refroidissement: 'Liquid Cooling 240mm', Alimentation: '600W Gold', Boîtier: 'Glass Panel' },
  colors: ['#1a1a1a', '#10b981'],
},
{
  id: 57,
  name: 'Acer Predator Galea 311 Casque Gaming',
  brand: 'Acer',
  category: 'audio',
  subcategory: 'casques',
  price: 79.99,
  originalPrice: 99.99,
  discount: 20,
  rating: 4.4,
  reviews: 234,
  stock: 25,
  sold: 345,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/acer speaker.jpg',
  images: ['./images/acer speaker.jpg'],
  description: 'Casque gaming Acer Predator Galea 311 avec audio spatial et micro détachable.',
  specs: { Type: 'Over-Ear', Drivers: '50mm néodyme', Fréquence: '20Hz-20KHz', Impédance: '32 Ohms', Micro: 'Détachable avec réduction de bruit', Connexion: '3.5mm + USB', Poids: '285g', Compatible: 'PC, PS4, Xbox, Switch' },
  colors: ['#1a1a1a'],
},
{
  id: 58,
  name: 'Logitech G533 Casque Gaming Wireless',
  brand: 'Logitech',
  category: 'audio',
  subcategory: 'casques',
  price: 149.99,
  originalPrice: 179.99,
  discount: 17,
  rating: 4.6,
  reviews: 345,
  stock: 18,
  sold: 456,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/logi headset.jfif',
  images: ['./images/logi headset.jfif'],
  description: 'Casque sans fil Logitech G533 avec audio surround 7.1 et 15h d\'autonomie.',
  specs: { Type: 'Over-Ear', Drivers: '40mm Pro-G', Connexion: 'Wireless 2.4GHz', Autonomie: '15 heures', Surround: 'DTS Headphone:X 7.1', Micro: 'Flip-to-mute avec réduction de bruit', Poids: '339g', Portée: '15 mètres' },
  colors: ['#1a1a1a'],
},
{
  id: 59,
  name: 'MSI Immerse GH60 Casque Gaming',
  brand: 'MSI',
  category: 'audio',
  subcategory: 'casques',
  price: 59.99,
  originalPrice: 79.99,
  discount: 25,
  rating: 4.4,
  reviews: 267,
  stock: 30,
  sold: 389,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/msi headset.png',
  images: ['./images/msi headset.png'],
  description: 'Casque gaming MSI Immerse GH60 avec audio Hi-Res et design ergonomique.',
  specs: { Type: 'Over-Ear', Drivers: '40mm', Fréquence: '20Hz-20KHz', Micro: 'Détachable avec réduction de bruit', Connexion: '3.5mm + USB', Poids: '265g', Compatible: 'Multi-plateforme', Certification: 'Hi-Res Audio' },
  colors: ['#1a1a1a', '#ef4444'],
},
{
  id: 60,
  name: 'Razer BlackShark V2 X Casque Gaming',
  brand: 'Razer',
  category: 'audio',
  subcategory: 'casques',
  price: 69.99,
  originalPrice: 89.99,
  discount: 22,
  rating: 4.5,
  reviews: 456,
  stock: 22,
  sold: 567,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/razer headset 2.jpg',
  images: ['./images/razer headset 2.jpg'],
  description: 'Casque gaming Razer BlackShark V2 X avec audio THX Spatial et design léger.',
  specs: { Type: 'Over-Ear', Drivers: '50mm Razer TriForce', Fréquence: '12Hz-28KHz', Audio: 'THX Spatial Audio', Micro: 'Cardioïde détachable', Connexion: '3.5mm', Poids: '240g', Compatible: 'PC, PS4, Xbox, Switch, Mobile' },
  colors: ['#1a1a1a', '#00ff00'],
},
{
  id: 61,
  name: 'HyperX Cloud II Casque Gaming',
  brand: 'HyperX',
  category: 'audio',
  subcategory: 'casques',
  price: 99.99,
  originalPrice: 119.99,
  discount: 17,
  rating: 4.7,
  reviews: 567,
  stock: 25,
  sold: 789,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/hyper headset.jpg',
  images: ['./images/hyper headset.jpg'],
  description: 'Le casque gaming le plus populaire avec audio 7.1 virtuel et confort exceptionnel.',
  specs: { Type: 'Over-Ear', Drivers: '53mm', Fréquence: '15Hz-25KHz', Audio: '7.1 virtuel', Micro: 'Détachable avec réduction de bruit', Connexion: '3.5mm + USB', Poids: '320g', Certification: 'TeamSpeak et Discord' },
  colors: ['#1a1a1a', '#ef4444'],
},
{
  id: 62,
  name: 'Logitech G435 Casque Gaming Wireless',
  brand: 'Logitech',
  category: 'audio',
  subcategory: 'casques',
  price: 79.99,
  originalPrice: 99.99,
  discount: 20,
  rating: 4.5,
  reviews: 234,
  stock: 20,
  sold: 345,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/logi speaker.png',
  images: ['./images/logi speaker.png'],
  description: 'Casque sans fil léger Logitech G435 avec double connexion sans fil et Lightsync.',
  specs: { Type: 'On-Ear', Drivers: '40mm', Connexion: 'Lightspeed + Bluetooth', Autonomie: '18 heures', Poids: '165g', Micro: 'Intégré beamforming', Compatible: 'PC, PS, Switch, Mobile', Multipoint: 'Oui' },
  colors: ['#1a1a1a', '#3b82f6', '#f472b6'],
},
{
  id: 63,
  name: 'HyperX QuadCast Micro USB',
  brand: 'HyperX',
  category: 'audio',
  subcategory: 'micros',
  price: 129.99,
  originalPrice: 149.99,
  discount: 13,
  rating: 4.7,
  reviews: 345,
  stock: 15,
  sold: 456,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/hyper mic.jpg',
  images: ['./images/hyper mic.jpg'],
  description: 'Micro USB studio HyperX QuadCast avec pattern cardioïde et anti-pop filter intégré.',
  specs: { Type: 'Condensateur USB', Patterns: 'Stéréo, Cardioïde, Bidirectionnel, Omnidirectionnel', Résolution: '16-bit/48kHz', Gain: 'Réglable', Mount: 'Shock mount intégré', LED: 'Indicateur muet', Bouton: 'Mute tactile instantané' },
  colors: ['#1a1a1a', '#ef4444'],
},
{
  id: 64,
  name: 'Logitech Blue Yeti Micro USB',
  brand: 'Logitech',
  category: 'audio',
  subcategory: 'micros',
  price: 119.99,
  originalPrice: 139.99,
  discount: 14,
  rating: 4.6,
  reviews: 567,
  stock: 20,
  sold: 789,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/logi mic.jpg',
  images: ['./images/logi mic.jpg'],
  description: 'Le micro USB le plus vendu au monde avec 4 patterns et qualité studio.',
  specs: { Type: 'Condensateur USB', Patterns: 'Cardioïde, Bidirectionnel, Omnidirectionnel, Stéréo', Résolution: '16-bit/48kHz', Gain: 'Réglable analogique', Mount: 'Stand inclus', ZeroLatency: 'Monitoring direct' },
  colors: ['#1a1a1a', '#c0c0c0', '#3b82f6', '#f472b6'],
},
{
  id: 65,
  name: 'Razer Seiren Mini Micro USB',
  brand: 'Razer',
  category: 'audio',
  subcategory: 'micros',
  price: 49.99,
  originalPrice: 59.99,
  discount: 17,
  rating: 4.5,
  reviews: 234,
  stock: 25,
  sold: 345,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/razer mic.jfif',
  images: ['./images/razer mic.jfif'],
  description: 'Micro USB compact Razer Seiren Mini avec pattern cardioïde ultra-directif.',
  specs: { Type: 'Condensateur USB', Pattern: 'Cardioïde fixe', Résolution: '16-bit/48kHz', Fréquence: '15Hz-18KHz', Mount: 'Stand incliné réglable', Design: 'Ultra-compact 14cm', PlugAndPlay: 'Oui' },
  colors: ['#1a1a1a'],
},
{
  id: 66,
  name: 'Écouteurs Wireless Cyberpunk RGB',
  brand: 'Generic',
  category: 'audio',
  subcategory: 'ecouteurs',
  price: 89.99,
  originalPrice: 119.99,
  discount: 25,
  rating: 4.4,
  reviews: 123,
  stock: 18,
  sold: 234,
  badge: 'new',
  isNew: true,
  isFeatured: false,
  isPopular: false,
  image: './images/wireless-earbuds-with-neon-cyberpunk-style-lighting.jpg',
  images: ['./images/wireless-earbuds-with-neon-cyberpunk-style-lighting.jpg'],
  description: 'Écouteurs sans fil avec éclairage néon cyberpunk et réduction de bruit active.',
  specs: { Type: 'In-Ear TWS', Connexion: 'Bluetooth 5.3', Autonomie: '6h + 24h boîtier', ANC: 'Réduction de bruit active', RGB: 'Éclairage néon personnalisable', Étanchéité: 'IPX5', Micro: 'Dual micros', Charge: 'USB-C' },
  colors: ['#1a1a1a', '#00ff00', '#ff00ff', '#00ffff'],
},
{
  id: 67,
  name: 'Acer Predator Keyboard Mechanical',
  brand: 'Acer',
  category: 'accessoires',
  subcategory: 'claviers',
  price: 129.99,
  originalPrice: 159.99,
  discount: 19,
  rating: 4.5,
  reviews: 189,
  stock: 15,
  sold: 234,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/acer keyboard.png',
  images: ['./images/acer keyboard.png'],
  description: 'Clavier mécanique Acer Predator avec switches rouges et RGB personnalisable.',
  specs: { Type: 'Mécanique', Switches: 'Rouges', Layout: 'AZERTY FR', Rétroéclairage: 'RGB personnalisable', NKeyRollover: 'Anti-ghosting', Frame: 'Aluminium', Poids: '1.2kg', Cable: 'Détachable USB-C' },
  colors: ['#1a1a1a'],
},
{
  id: 68,
  name: 'Logitech G915 TKL Mechanical Keyboard',
  brand: 'Logitech',
  category: 'accessoires',
  subcategory: 'claviers',
  price: 199.99,
  originalPrice: 249.99,
  discount: 20,
  rating: 4.7,
  reviews: 234,
  stock: 12,
  sold: 345,
  badge: 'promo',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/logi keyboard.png',
  images: ['./images/logi keyboard.png'],
  description: 'Clavier mécanique ultra-mince Logitech G915 TKL avec switches GL et Lightsync.',
  specs: { Type: 'Mécanique TKL', Switches: 'GL Tactile', Layout: 'AZERTY FR', Rétroéclairage: 'Lightsync RGB', Épaisseur: '22mm', Batterie: '40h (RGB) / 120h (off)', Connexion: 'Lightspeed + Bluetooth', Poids: '810g' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
  id: 69,
  name: 'Razer BlackWidow V3 Mechanical Keyboard',
  brand: 'Razer',
  category: 'accessoires',
  subcategory: 'claviers',
  price: 159.99,
  originalPrice: 189.99,
  discount: 16,
  rating: 4.6,
  reviews: 345,
  stock: 18,
  sold: 456,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/razer keyboard.jfif',
  images: ['./images/razer keyboard.jfif'],
  description: 'Clavier mécanique Razer BlackWidow V3 avec switches vertes et Chroma RGB.',
  specs: { Type: 'Mécanique', Switches: 'Razer Green', Layout: 'AZERTY FR', Rétroéclairage: 'Chroma RGB 16.8M', WristRest: 'Inclus magnétique', Passecâbles: 'Oui', MediaKeys: 'Dédier', Frame: 'Aluminium' },
  colors: ['#1a1a1a', '#00ff00'],
},
{
  id: 70,
  name: 'Corsair Harpoon RGB Mouse',
  brand: 'Corsair',
  category: 'accessoires',
  subcategory: 'souris',
  price: 39.99,
  originalPrice: 49.99,
  discount: 20,
  rating: 4.5,
  reviews: 456,
  stock: 25,
  sold: 567,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/corsair mouse.jpg',
  images: ['./images/corsair mouse.jpg'],
  description: 'Souris gaming Corsair Harpoon RGB avec capteur 10000 DPI et design ergonomique.',
  specs: { Capteur: 'Optique 10000 DPI', Boutons: '6 programmables', Poids: '85g', Switches: 'Omron 50M clics', RGB: '4 zones', PollingRate: '1000Hz', Surface: 'Caoutchouc texturé', Cable: 'Tressé' },
  colors: ['#1a1a1a', '#6366f1'],
},
{
  id: 71,
  name: 'Logitech G502 HERO Mouse',
  brand: 'Logitech',
  category: 'accessoires',
  subcategory: 'souris',
  price: 49.99,
  originalPrice: 59.99,
  discount: 17,
  rating: 4.7,
  reviews: 678,
  stock: 30,
  sold: 890,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/g502.jpg',
  images: ['./images/g502.jpg'],
  description: 'La souris gaming la plus vendue avec capteur HERO 25K et 11 boutons programmables.',
  specs: { Capteur: 'HERO 25K 25600 DPI', Boutons: '11 programmables', Poids: '121g (ajustable)', Switches: 'Omron mécaniques 50M', RGB: '1 zone', Scroll: 'Infini + précision', Poids: '5 masses ajustables' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
  id: 72,
  name: 'Logitech MX Master 3S Mouse',
  brand: 'Logitech',
  category: 'accessoires',
  subcategory: 'souris',
  price: 99.99,
  originalPrice: 119.99,
  discount: 17,
  rating: 4.8,
  reviews: 345,
  stock: 15,
  sold: 456,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/mx-master-logitech.webp',
  images: ['./images/mx-master-logitech.webp'],
  description: 'Souris ergonomique premium pour productivité avec scroll MagSpeed et multi-device.',
  specs: { Capteur: '8000 DPI silencieux', Boutons: '7 programmables', Poids: '141g', Scroll: 'MagSpeed électromagnétique', Connexion: 'Bluetooth + USB Receiver', Multidevice: 'Jusqu\'à 3 appareils', Autonomie: '70 jours' },
  colors: ['#1a1a1a', '#c0c0c0', '#d4a483'],
},
{
  id: 73,
  name: 'Razer DeathAdder V2 Mouse',
  brand: 'Razer',
  category: 'accessoires',
  subcategory: 'souris',
  price: 69.99,
  originalPrice: 79.99,
  discount: 13,
  rating: 4.6,
  reviews: 456,
  stock: 20,
  sold: 567,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/razer mouse.jfif',
  images: ['./images/razer mouse.jfif'],
  description: 'Souris gaming ergonomique Razer DeathAdder V2 avec capteur Focus+ et switches optiques.',
  specs: { Capteur: 'Focus+ 20000 DPI', Boutons: '8 programmables', Poids: '82g', Switches: 'Optiques 70M clics', RGB: 'Chroma RGB', Forme: 'Ergonomique droit', Cable: 'Speedflex tressé' },
  colors: ['#1a1a1a', '#00ff00'],
},
{
  id: 74,
  name: 'Logitech G Pro Mouse',
  brand: 'Logitech',
  category: 'accessoires',
  subcategory: 'souris',
  price: 79.99,
  originalPrice: 99.99,
  discount: 20,
  rating: 4.7,
  reviews: 234,
  stock: 18,
  sold: 345,
  badge: 'popular',
  isNew: false,
  isFeatured: true,
  isPopular: true,
  image: './images/logi mouse.jpg',
  images: ['./images/logi mouse.jpg'],
  description: 'Souris gaming professionnelle Logitech G Pro avec capteur HERO et design ultra-léger.',
  specs: { Capteur: 'HERO 25600 DPI', Boutons: '5 programmables', Poids: '63g (ultra-léger)', Switches: 'Mechanical', RGB: '1 zone', Cable: 'Détachable', Forme: 'Ambidextre compacte' },
  colors: ['#1a1a1a', '#c0c0c0', '#f472b6'],
},
{
  id: 75,
  name: 'Samsung Galaxy Watch 5',
  brand: 'Samsung',
  category: 'accessoires',
  subcategory: 'montres',
  price: 279.99,
  originalPrice: 329.99,
  discount: 15,
  rating: 4.6,
  reviews: 234,
  stock: 15,
  sold: 345,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/galaxy watch.jpg',
  images: ['./images/galaxy watch.jpg'],
  description: 'Montre connectée Samsung Galaxy Watch 5 avec suivi santé avancé et autonomie 40h.',
  specs: { Taille: '44mm', Écran: 'Super AMOLED 1.4" 450x450', OS: 'Wear OS', Processeur: 'Exynos W920', RAM: '1.5 Go', Stockage: '16 Go', Batterie: '410 mAh (40h)', Capteurs: 'ECG, SpO2, FC, GPS' },
  colors: ['#1a1a1a', '#c0c0c0', '#8B7355'],
},
{
  id: 76,
  name: 'Samsung Galaxy Watch 4',
  brand: 'Samsung',
  category: 'accessoires',
  subcategory: 'montres',
  price: 199.99,
  originalPrice: 249.99,
  discount: 20,
  rating: 4.5,
  reviews: 345,
  stock: 20,
  sold: 456,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/galaxy watch4.jpg',
  images: ['./images/galaxy watch4.jpg'],
  description: 'Montre connectée Samsung Galaxy Watch 4 avec BioActive Sensor et Wear OS.',
  specs: { Taille: '44mm', Écran: 'Super AMOLED 1.4" 450x450', OS: 'Wear OS', Processeur: 'Exynos W920', RAM: '1.5 Go', Stockage: '16 Go', Batterie: '361 mAh', Capteurs: 'BioActive Sensor 3-en-1' },
  colors: ['#1a1a1a', '#c0c0c0', '#3b82f6'],
},
{
  id: 77,
  name: 'Smart Fit Tracker',
  brand: 'Smart Fit',
  category: 'accessoires',
  subcategory: 'fitness',
  price: 49.99,
  originalPrice: 69.99,
  discount: 29,
  rating: 4.3,
  reviews: 234,
  stock: 30,
  sold: 345,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/smart fit.jpg',
  images: ['./images/smart fit.jpg'],
  description: 'Bracelet fitness avec suivi d\'activité, moniteur cardiaque et étanchéité IP68.',
  specs: { Écran: 'OLED 0.96"', Capteurs: 'FC, SpO2, sommeil', Autonomie: '14 jours', Étanchéité: 'IP68', Sports: '100+ modes', Notifications: 'Appels et messages', Charge: 'Magnétique' },
  colors: ['#1a1a1a', '#c0c0c0', '#3b82f6', '#f472b6'],
},
{
  id: 78,
  name: 'SteelSeries QcK XL Tapis Souris',
  brand: 'SteelSeries',
  category: 'accessoires',
  subcategory: 'tapis',
  price: 29.99,
  originalPrice: 39.99,
  discount: 25,
  rating: 4.6,
  reviews: 567,
  stock: 40,
  sold: 789,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/steelseries xl.jfif',
  images: ['./images/steelseries xl.jfif'],
  description: 'Tapis de souris XL SteelSeries QcK avec surface en tissu de haute qualité.',
  specs: { Dimensions: '900 x 300 x 3 mm', Surface: 'Tissu micro-texturé', Base: 'Caoutchouc anti-dérapant', Épaisseur: '3mm', Compatible: 'Optique et laser', Lavable: 'Oui' },
  colors: ['#1a1a1a'],
},
{
  id: 79,
  name: 'Onida TV 32" HD Smart',
  brand: 'Onida',
  category: 'electronique',
  subcategory: 'televisions',
  price: 249.99,
  originalPrice: 299.99,
  discount: 17,
  rating: 4.3,
  reviews: 123,
  stock: 15,
  sold: 234,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/onidatv.jpg',
  images: ['./images/onidatv.jpg'],
  description: 'TV Onida 32" HD Ready Smart avec Android TV et Dolby Audio.',
  specs: { Écran: '32" HD Ready 1366x768', Processeur: 'Quad Core', SmartTV: 'Android TV', Audio: 'Dolby Audio', Ports: '2x HDMI, 2x USB', Connectivité: 'Wi-Fi, Chromecast built-in' },
  colors: ['#1a1a1a'],
},
{
  id: 80,
  name: 'DALI IO-6',
  brand: 'DALI',
  category: 'accessoires',
  subcategory: 'autres',
  price: 29.99,
  originalPrice: 39.99,
  discount: 25,
  rating: 4.2,
  reviews: 89,
  stock: 50,
  sold: 123,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/product_img4.png',
  images: ['./images/product_img4.png'],
  description: 'Accessoire tech polyvalent pour usage quotidien.',
  specs: { Type: 'Accessoire', Matière: 'Plastique premium', Dimensions: 'Standard', Compatible: 'Multi-plateforme', Garantie: '1 an' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
  id: 81,
  name: ' BOAT Aavante Bar 3600',
  brand: 'BOAT',
  category: 'accessoires',
  subcategory: 'autres',
  price: 34.99,
  originalPrice: 44.99,
  discount: 22,
  rating: 4.3,
  reviews: 67,
  stock: 45,
  sold: 89,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/product_img8.png',
  images: ['./images/product_img8.png'],
  description: 'Accessoire tech avec design moderne et fonctionnalités pratiques.',
  specs: { Type: 'Accessoire', Matière: 'Aluminium', Dimensions: 'Compact', Compatible: 'Universal', Garantie: '1 an' },
  colors: ['#1a1a1a', '#3b82f6'],
},
{
  id: 82,
  name: 'Apple AirPods Pro',
  brand: 'AirPods',
  category: 'accessoires',
  subcategory: 'autres',
  price: 39.99,
  originalPrice: 49.99,
  discount: 20,
  rating: 4.4,
  reviews: 78,
  stock: 40,
  sold: 112,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/product_img9.png',
  images: ['./images/product_img9.png'],
  description: 'Accessoire tech premium avec finitions de qualité.',
  specs: { Type: 'Accessoire', Matière: 'Métal', Dimensions: 'Standard', Compatible: 'Multi-usage', Garantie: '2 ans' },
  colors: ['#1a1a1a', '#c0c0c0', '#f59e0b'],
},
{
  id: 83,
  name: 'ILIFE A20 Pro',
  brand: 'Aspirateur',
  category: 'electromenager',
  subcategory: 'autres',
  price: 54.99,
  originalPrice: 64.99,
  discount: 15,
  rating: 4.5,
  reviews: 34,
  stock: 25,
  sold: 56,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/product_img12.png',
  images: ['./images/product_img12.png'],
  description: 'Accessoire tech professionnel avec fonctionnalités avancées.',
  specs: { Type: 'Accessoire', Matière: 'Aluminium anodisé', Dimensions: 'Pro', Compatible: 'Professional', Garantie: '2 ans' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
  id: 84,
  name: 'Sony PlayStation 5',
  brand: 'PlayStation',
  category: 'accessoires',
  subcategory: 'autres',
  price: 64.99,
  originalPrice: 74.99,
  discount: 13,
  rating: 4.5,
  reviews: 18,
  stock: 18,
  sold: 34,
  badge: 'popular',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/product_img14.png',
  images: ['./images/product_img14.png'],
  description: 'Accessoire tech premium avec finitions haut de gamme.',
  specs: { Type: 'Accessoire', Matière: 'Cuir et métal', Dimensions: 'Luxe', Compatible: 'Premium', Garantie: '2 ans' },
  colors: ['#1a1a1a', '#d4a483'],
},
{
  id: 85,
  name: 'Réfrigérateur Samsung Inox',
  brand: 'Samsung',
  category: 'electromenager',
  subcategory: 'refrigerateurs',
  price: 899.99,
  originalPrice: 1199.99,
  discount: 25,
  rating: 4.6,
  reviews: 156,
  stock: 5,
  sold: 203,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/1.jpg',
  images: ['./images/1.jpg'],
  description: 'Réfrigérateur Samsung avec technologie Inox et espace généreux pour toute la famille.',
  specs: { Capacité: '500 L', Classe: 'A++', Couleur: 'Inox', Dimensions: 'H 185x L 90x P 70 cm', Garantie: '2 ans' },
  colors: ['#c0c0c0', '#1a1a1a'],
},
{
  id: 86,
  name: 'Climatiseur',
  brand: 'Climatiseur',
  category: 'electromenager',
  subcategory: 'lave-linge',
  price: 31.99,
  originalPrice: 35.18,
  discount: 10,
  rating: 4.5,
  reviews: 234,
  stock: 6,
  sold: 389,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/2.jpg',
  images: ['./images/2.jpg'],
  description: 'Un boîtier horizontal qui aspire l\'air ambiant, le fait passer à travers plusieurs couches de filtration, puis rejette un air propre.',
  specs: { Capacité: '9 kg', Essorage: '1400 tr/min', Classe: 'A', Programmes: '14 programmes' },
  colors: ['#ffffff', '#c0c0c0'],
},
{
  id: 87,
  name: 'Radiateur portable Warmwave',
  brand: 'Radiateur',
  category: 'electromenager',
  subcategory: 'lave-vaisselle',
  price: 499.99,
  originalPrice: 649.99,
  discount: 23,
  rating: 4.7,
  reviews: 189,
  stock: 8,
  sold: 267,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: true,
  image: './images/3.jpg',
  images: ['./images/3.jpg'],
  description: 'Lave-vaisselle Bosch ultra-silencieux avec capacité 13 couverts et programme éco.',
  specs: { Marque: 'Warmwave 1500-Watt', Fonstionnalités: 'Comprend des réglages de chaleur doubles et un thermostat réglable.', Sécurité : 'Dispose d\'un témoin lumineux' },
  colors: ['#ffffff', '#1a1a1a'],
},
{
  id: 88,
  name: 'Stimulateur DPE',
  brand: 'Stimulateur',
  category: 'electromenager',
  subcategory: 'fours',
  price: 390.04,
  originalPrice: 499.99,
  discount: 22,
  rating: 4.6,
  reviews: 145,
  stock: 4,
  sold: 178,
  badge: 'promo',
  isNew: false,
  isFeatured: false,
  isPopular: false,
  image: './images/4.jpg',
  images: ['./images/4.jpg'],
  description: 'Un appareil conçu pour fournir de la chaleur dans les espaces extérieurs comme les terrasses de restaurants ou les jardins.',
  specs: { Fonctionnement: 'Gaz propane ou butane', Puissance: '13kw', Nettoyage: 'Grille anti-poussière' , Sécurité: 'Thermocouple et antibasculement' },
  colors: ['#1a1a1a', '#c0c0c0'],
},
{
    id: 89,
    name: 'Capteur de température et d\'humidité ZigBee SNZB-02D',
    brand: 'Capteur',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 19.99,
    originalPrice: 22.99,
    discount: 15,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: false,
    image: './images/M1.png',
    images: ['./images/M1.png'],
    description: 'Il est équipé d\'un écran LCD haute définition affichant les données de température et d\'humidité en temps réel, pour une lecture intuitive et facile.',
    specs: { Alimentation : 'Pile 3V CR2450 fournie', Frequence:'2.4GHz', Dimensions : '59.5mm x 62.5mm x 18.5 mm',  Température :'-9.9°C à 60°C', Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 90,
    name: 'Pack radio ZigBee',
    brand: 'ZigBee',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 310.45,
    originalPrice: 357.02,
    discount: 15,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/M2.png',
    images: ['./images/M2.png'],
    description: 'Ce pack a été spécialement conçu pour piloter vos équipements de chauffage sans box internet à distance.',
    specs: { Alimentation : 'cordon secteur (85 – 265VAC @ 47 – 440Hz)', Frequence:'2.4GHz', Dimensions : '70 x 58 x 90 mm',  Température :' -10°C à +40°C', Puissance :  '1W en fonctionnement, hors communication GSM et sortie inactive' , Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 91,
    name: 'Module fil pilote',
    brand: 'Module',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 12.75,
    originalPrice: 14.25,
    discount: 10,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/M3.png',
    images: ['./images/M3.png'],
    description: 'Module permettant la génération d\'un ordre fil pilote pour vos équipements de chauffage pilotés par un fil pilote.',
    specs: { Borne : 'Phase et Radiateur',  Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 92,
    name: 'Thermostat d\'ambiance filaire pour chauffage',
    brand: 'Thermostat',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 35.45,
    originalPrice: 40.76,
    discount: 15,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/M4.png',
    images: ['./images/M4.png'],
    description: 'Ce thermostat possède un contact de sortie en « tout ou rien ».',
    specs: { Dimensions : '82 x 75 x 31 mm',  Température :' 6°C à 30°C', Puissance :  '10A sur charge résistive' , Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 93,
    name: 'Cleaner Pro° Haute Pression',
    brand: 'Cleaner',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 75.90,
    originalPrice: 87.30,
    discount: 15,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/E1.png',
    images: ['./images/E1.png'],
    description: 'Permet un nettoyage puissant et rapide, éliminant facilement les taches tenaces sur toutes les surfaces.',
    specs: { Alimentation : 'Batterie lithium rechargeable, chargeable en voiture', Poids:'1,3 kg', Dimensions : '260 × 160 × 160 mm', Puissance :  '300 W', Débit : '8 à 10 L/min pour un nettoyage rapide' , Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 94,
    name: 'Diffuseur d\'Arômes - FlameZen',
    brand: 'Arômes',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 50.25,
    originalPrice: 56.28,
    discount: 12,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/E2.png',
    images: ['./images/E2.png'],
    description: 'Diffusez vos huiles essentielles préférées et transformez votre maison en un sanctuaire de bien-être. Idéal pour la relaxation, la méditation ou simplement créer une atmosphère apaisante.',
    specs: { Capacité : '150ml', Volume:'20-25 ml/h', Dimensions : '21.8 x 8.5 x 10.7 cm', Alimentation :  'Adaptateur 5V2A (non inclus)', Fonctionnement : '30dB' , Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 95,
    name: 'FlexiMist Pro™ – Système d\'Irrigation Intelligent à 360°',
    brand: 'FlexiMist',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 45.25,
    originalPrice: 50.68,
    discount: 12,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 450,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/E3.png',
    images: ['./images/E3.png'],
    description: 'Grâce à ses buses en cuivre orientables à 360° et réglables, vous pouvez cibler la brume exactement là où vos plantes en ont besoin : racines, feuillage ou fleurs délicates. Fini le gaspillage, chaque goutte compte.',
    specs: { Pression : '1.5 – 3 bars', Débit:'8 à 10 L/h', Longueur : '20cm', Support :  '19cm', Température : '1 à 50°C' , Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 96,
    name: 'Nettoyeur de Surfaces Haute Pression - Washer Pro 2.0',
    brand: 'Nettoyeur',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 145.80,
    originalPrice: 163.30,
    discount: 12,
    rating: 4.5,
    reviews: 234,
    stock: 19,
    sold: 425,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/E4.png',
    images: ['./images/E4.png'],
    description: 'Le Washer Pro est conçu pour que même les tâches les plus pénibles deviennent simples. Dites adieu à la fatigue et aux douleurs grâce à son design ergonomique et ses performances exceptionnelles.',
    specs: { Pression : '12500 PSI', Matériaux:'Acier inoxydable, laiton et plastique durable', Connectivité : 'Connexion rapide 1/4, compatible avec la plupart des nettoyeurs haute pression (y compris les modèles Karcher K1 à K7)' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 97,
    name: 'Mini Scie à Élaguer Sans Fil - PowerTrim Pro',
    brand: 'Scie',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 100.30,
    originalPrice: 110.33,
    discount: 10,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/E5.png',
    images: ['./images/E5.png'],
    description: 'Avec le moteur en cuivre sans balais, réalisez vos travaux rapidement et efficacement. La puissance stable évite toute surchauffe et garantit une longue durée de vie à votre outil.',
    specs: { Puissance : '3000W', Vitesse:'5 m/s', Poids : '1,14 kg', Batterie :  '2.0Ah à 5.0Ah' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 98,
    name: 'Marmite Stainless Steel',
    brand: "Marmite",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 149.94,
    originalPrice: 179.99,
    discount: 17,
    rating: 4.6,
    reviews: 312,
    stock: 7,
    sold: 445,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C1.png',
    images: ['./images/C1.png'],
    description: 'Marmite à soupe pour les très grands projets de cuisson. Idéale pour préparer une grande portion de soupe, des plats mijotés, des poulets entiers ou du bouillon maison.',
    specs: { Matériau: 'Acier inoxydable', Capacité: '5L', Dimensions: '30 x 25 x 15 cm', Poids: '2.5 kg', Garantie: '2 ans' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 99,
    name: 'Stainless steel batterie de cuisine - 5 pièces',
    brand: "Stainless",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 419.94,
    originalPrice: 499.99,
    discount: 15,
    rating: 4.6,
    reviews: 312,
    stock: 7,
    sold: 445,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C2.png',
    images: ['./images/C2.png'],
    description: 'Un set complet de marmites et de poêles pour répondre à tous vos besoins culinaires quotidiens.',
    specs: { Matériau: 'Acier inoxydable', Dimensions: '51.5 x 31 x 15 cm', Poids: '4.33 kg', Garantie: '2 ans' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 100,
    name: 'Tireuse à bière',
    brand: "Tireuse à bière",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 139.94,
    originalPrice: 158.73,
    discount: 12,
    rating: 4.6,
    reviews: 312,
    stock: 10,
    sold: 445,
    badge: 'popular',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C3.png',
    images: ['./images/C3.png'],
    description: 'Idéal pour tous ceux qui souhaitent profiter du goût et de la texture d\'une bière fraîchement tirée.',
    specs: { Alimentation: 'Cable USB', Dimensions: '58,93 x 25,4 x 44,45 cm', Poids: '2,13 kg', Garantie: '2 ans' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 101,
    name: 'Machine à granité',
    brand: "Machine à granité",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 229.30,
    originalPrice: 265.70,
    discount: 15,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'popular',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C4.png',
    images: ['./images/C4.png'],
    description: 'Granité fruité, milkshake crémeux, cocktail glacé, frappé ou même vin parfaitement tempéré : rien de plus simple avec cet appareil polyvalent.',
    specs: { Puissance: '220W', Dimensions: '47,6 x 45,8 x 24 cm', Poids: '10,7 kg', Garantie: '2 ans' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 102,
    name: 'Appareils de cuisine sans fil XTEND',
    brand: "Appareil de cuisine",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 259.15,
    originalPrice: 285.15,
    discount: 10,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'promo',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C5.png',
    images: ['./images/C5.png'],
    description: 'Au-delà de leur apparence iconique, leur design est pensé pour l\'efficacité, le confort et la durabilité. ',
    specs: { Batterie: 'lithium-ion 12 V / 3 Ah', Autonomie: '1h', Garantie: '2 ans' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 103,
    name: 'Trancheur universel ultra-compact',
    brand: "Trancheur",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 259.95,
    originalPrice: 301.15,
    discount: 15,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'popular',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C6.png',
    images: ['./images/C6.png'],
    description: 'Ce trancheur puissant n\'occupe sur votre plan de travail guère plus de place qu\'une feuille A4.',
    specs: { Puissance: '45 W', Dimensions: ' 34 x 23 x 18 cm', Poids: '3,3 kg', Garantie: '2 ans' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 104,
    name: 'Raclette-grill 5-en-1 Solis',
    brand: "Raclette",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 230.15,
    originalPrice: 266.59,
    discount: 15,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'popular',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C7.png',
    images: ['./images/C7.png'],
    description: 'Grâce à la chaleur supérieure et inférieure, les barbecues et plats grillés réussissent à la perfection.',
    specs: { Puissance: '1400 W', Dimensions: ' 56 x 15 x 27 cm', Poids: '5,3 kg', Garantie: '2 ans' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 105,
    name: 'Appareils de cuisine Jacob Jensen',
    brand: "Jacob Jensen",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 199.99,
    originalPrice: 257.36,
    discount: 13,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C8.png',
    images: ['./images/C8.png'],
    description: 'Sept niveaux de brunissage précis, une fonction bagel, une fonction réchauffage et décongélation ainsi qu\'un minuteur transforment le grillage en expérience design.',
    specs: { Puissance: '1850 W', Dimensions: '  26 x 23 x 16 cm', Poids: '2,55 kg', Garantie: '2 ans', Température: '70 °C à 100 °C' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 106,
    name: 'Four à pizza',
    brand: "Four",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 169.95,
    originalPrice: 195.47,
    discount: 13,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C9.png',
    images: ['./images/C9.png'],
    description: 'La pierre de chauffe en cordiérite naturelle emmagasine la chaleur de manière optimale et absorbe l\'humidité excédentaire de la pâte à pizza.',
    specs: { Puissance: '2200 W', Dimensions: ' 46 x 28,9 x 48,5 cm', Poids: '12,15 kg', Garantie: '2 ans', Température: '430 °C' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 107,
    name: 'Refroidisseur à vin design sur batterie',
    brand: "Refroidisseur",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 179.95,
    originalPrice: 205.13,
    discount: 13,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'promo',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C10.png',
    images: ['./images/C10.png'],
    description: 'Ce refroidisseur à vin élégant et fonctionnant sur batterie maintient votre vin pré-réfrigéré à la température idéale de consommation du premier au dernier verre, tout en mettant parfaitement en valeur les élégantes gouttes.',
    specs: { Dimensions: '13,5 x 24,5 x 28 cm', Poids: '2,3 kg', Garantie: '2 ans', Température: '5 à 18 °C' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 108,
    name: 'Refroidisseur à vin design sur batterie',
    brand: "Refroidisseur",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 199.99,
    originalPrice: 227.13,
    discount: 13,
    rating: 4.6,
    reviews: 310,
    stock: 15,
    sold: 445,
    badge: 'promo',
    isNew: true,
    isFeatured: false,
    isPopular: true,
    image: './images/C11.png',
    images: ['./images/C11.png'],
    description: 'Tout ce que vous attendez d\'une machine à expresso à porte-filtre de bonne qualité : un système professionnel à blocage thermique double avec fonction de pré-infusion.',
    specs: { Dimensions: '21,5 x 31 x 32 cm', Poids: '4,6 kg', Garantie: '2 ans', Puissance: '1350W' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 109,
    name: 'KIT ALARME VESTA PREMIUM 4G HD',
    brand: 'Alarme',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 1362.62,
    originalPrice: 1633.14,
    discount: 15,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/M5.png',
    images: ['./images/M5.png'],
    description: 'Le Kit Alarme VESTA PREMIUM 4G HD est une configuration experte conçue par Domotec Services, destinée à assurer une protection complète et autonome des habitations. Il associe détection périmétrique, détection intérieure avec levée de doute photo, alerte sonore dissuasive et transmission 4G sécurisée.',
    specs: { Wifi: '4G',  Supervision:'Via Appareil Mobile', Gestion: 'Multi-Plateformes', Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 110,
    name: 'YASHE Mini réfrigérateur',
    brand: 'YASHE',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 65.99,
    originalPrice: 79.99,
    discount: 12,
    rating: 4.5,
    reviews: 234,
    stock: 19,
    sold: 425,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/E6.png',
    images: ['./images/E6.png'],
    description: 'Le mini-réfrigérateur YASHE est conçu pour un stockage polyvalent, parfait pour la nourriture, les boissons, les collations, le lait maternel, le maquillage, les cosmétiques et les soins de la peau. Idéal pour les chambres, les bureaux, les dortoirs, les voyages, la navigation, le camping et plus encore.',
    specs: { Dimensions: '18 x 26 x 32 cm', Poids: '4,6 kg', Garantie: '2 ans', Température: '18 à 20 °C ambiante et 1 à 2 °C interne', Capacité: '6L' },
    colors: ['#000000', '#c0c0c0'],
  },
  {
    id: 111,
    name: 'FOHERE Mini Frigo',
    brand: 'FOHERE',
    category: 'electromenager',
    subcategory: 'purificateurs',
    price: 45.99,
    originalPrice: 50.59,
    discount: 10,
    rating: 4.5,
    reviews: 234,
    stock: 19,
    sold: 425,
    badge: 'new',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: './images/E7.png',
    images: ['./images/E7.png'],
    description: 'Qu\'il s\'agisse de boissons, de fruits, de produits de soins de la peau et de médicaux, que ce soit à la maison ou à l\'extérieur, ce mini glacière de petit volume est très approprié. ',
    specs: { Dimensions: '19,6x 26,3 x 28,6 cm', Poids: '1,8 kg', Garantie: '2 ans', Température: '18 à 20 °C ambiante et 1 à 2 °C interne', Capacité: '5L' },
    colors: ['#000000', '#c0c0c0'],
  },
];

// Helper functions
function getProductById(id) {
  return PRODUCTS.find(p => p.id === parseInt(id));
}

function getProductsByCategory(cat) {
  if (!cat || cat === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === cat);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => p.isFeatured);
}

function getPopularProducts() {
  return PRODUCTS.filter(p => p.isPopular);
}

function getNewProducts() {
  return PRODUCTS.filter(p => p.isNew);
}

function getRelatedProducts(product, count = 4) {
  return PRODUCTS
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, count);
}

function filterProducts(filters = {}) {
  let result = [...PRODUCTS];

  if (filters.category && filters.category !== 'all') {
    result = result.filter(p => p.category === filters.category);
  }
  if (filters.brands && filters.brands.length > 0) {
    result = result.filter(p => filters.brands.includes(p.brand));
  }
  if (filters.minPrice !== undefined) {
    result = result.filter(p => p.price >= filters.minPrice);
  }
  if (filters.maxPrice !== undefined) {
    result = result.filter(p => p.price <= filters.maxPrice);
  }
  if (filters.minRating !== undefined) {
    result = result.filter(p => p.rating >= filters.minRating);
  }
  if (filters.badge) {
    result = result.filter(p => p.badge === filters.badge);
  }
  if (filters.inStock) {
    result = result.filter(p => p.stock > 0);
  }
  if (filters.search) {
    const q = filters.search.toLowerCase();
    result = result.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
    );
  }

  // Sort
  switch (filters.sort) {
    case 'price-asc': result.sort((a, b) => a.price - b.price); break;
    case 'price-desc': result.sort((a, b) => b.price - a.price); break;
    case 'rating': result.sort((a, b) => b.rating - a.rating); break;
    case 'popular': result.sort((a, b) => b.sold - a.sold); break;
    case 'new': result.sort((a, b) => (b.isNew ? 1 : 0) - (a.isNew ? 1 : 0)); break;
    default: break;
  }

  return result;
}

function formatPrice(price) {
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(price);
}

function renderStars(rating) {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5;
  let html = '';
  for (let i = 1; i <= 5; i++) {
    if (i <= full) html += '★';
    else if (i === full + 1 && half) html += '⯨';
    else html += '☆';
  }
  return html;
}
