/* ============================================================
   ELECTRONOVA - Products & Categories Data
   ============================================================ */

const CATEGORIES = [
  { id: 'electromenager', name: 'Électroménager', icon: '🏠', color: '#dbeafe', count: 48, sub: ['Réfrigérateurs', 'Machines à laver', 'Lave-vaisselle', 'Fours & Cuisinières', 'Climatiseurs', 'Aspirateurs'] },
  { id: 'electronique', name: 'Électronique', icon: '📱', color: '#e0e7ff', count: 63, sub: ['Téléviseurs', 'Smartphones', 'Laptops & PC', 'Tablettes', 'Appareils photo', 'Consoles'] },
  { id: 'cuisine', name: 'Ustensiles Cuisine', icon: '🍳', color: '#fef9c3', count: 35, sub: ['Robots culinaires', 'Cafetières', 'Blenders', 'Grille-pain', 'Micro-ondes', 'Friteuses'] },
  { id: 'audio', name: 'Audio & Son', icon: '🎧', color: '#fce7f3', count: 42, sub: ['Casques audio', 'Enceintes', 'Barres de son', 'Écouteurs', 'Amplis Hi-Fi'] },
  { id: 'smart-home', name: 'Maison Connectée', icon: '💡', color: '#d1fae5', count: 27, sub: ['Éclairage LED', 'Sonnettes vidéo', 'Thermostats', 'Sécurité', 'Assistants vocaux'] },
  { id: 'accessoires', name: 'Accessoires Tech', icon: '🔌', color: '#ffedd5', count: 89, sub: ['Chargeurs', 'Câbles', 'Supports', 'Coques', 'Clés USB & stockage'] },
];

const BRANDS = ['Samsung', 'Apple', 'Sony', 'LG', 'Philips', 'Bosch', 'Dyson', 'Bose', 'Tefal', 'Xiaomi'];

const PRODUCTS = [
  {
    id: 1,
    name: 'Samsung Neo QLED 65" 4K Smart TV',
    brand: 'Samsung',
    category: 'electronique',
    subcategory: 'televisions',
    price: 1299.99,
    originalPrice: 1799.99,
    discount: 28,
    rating: 4.8,
    reviews: 234,
    stock: 8,
    sold: 312,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=600&q=80&fit=crop',
      'https://images.unsplash.com/photo-1571415173083-2dc5c7f5b06e?w=600&q=80&fit=crop',
      'https://images.unsplash.com/photo-1601944177325-f8867652837f?w=600&q=80&fit=crop',
    ],
    description: 'Vivez une expérience visuelle exceptionnelle avec cette Smart TV Neo QLED 4K Samsung. Technologie Quantum Mini LED pour des noirs profonds et des contrastes saisissants.',
    specs: { Résolution: '4K Ultra HD 3840x2160', Technologie: 'Neo QLED', Taille: '65 pouces', Processeur: 'Neural Quantum 4K', HDR: 'HDR10+', 'Fréquence': '120Hz', 'Smart TV': 'Tizen OS', Ports: '4x HDMI, 3x USB' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 2,
    name: 'iPhone 15 Pro Max 256Go',
    brand: 'Apple',
    category: 'electronique',
    subcategory: 'smartphones',
    price: 1329.00,
    originalPrice: 1329.00,
    discount: 0,
    rating: 4.9,
    reviews: 567,
    stock: 15,
    sold: 892,
    badge: 'popular',
    isNew: true,
    isFeatured: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&q=80&fit=crop',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80&fit=crop',
    ],
    description: 'Le iPhone 15 Pro Max redéfinit les standards avec sa puce A17 Pro, son écran Super Retina XDR 6.7" et son système de caméra de 48MP.',
    specs: { Écran: '6.7" Super Retina XDR', Processeur: 'A17 Pro', Stockage: '256 Go', RAM: '8 Go', Caméra: '48 MP + 12 MP + 12 MP', 'Caméra Frontale': '12 MP TrueDepth', Batterie: '4422 mAh', OS: 'iOS 17' },
    colors: ['#8B7355', '#1a1a1a', '#4a4a4a', '#C8C3BC'],
  },
  {
    id: 3,
    name: 'Sony WH-1000XM5 Casque Bluetooth',
    brand: 'Sony',
    category: 'audio',
    subcategory: 'casques',
    price: 279.99,
    originalPrice: 349.99,
    discount: 20,
    rating: 4.9,
    reviews: 1204,
    stock: 22,
    sold: 1540,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&q=80&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=600&q=80&fit=crop',
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&q=80&fit=crop',
    ],
    description: 'La référence en matière de réduction de bruit active. Le WH-1000XM5 offre une qualité sonore HD et une autonomie de 30 heures.',
    specs: { Type: 'Over-Ear', Connexion: 'Bluetooth 5.2', 'Réduction de bruit': 'ANC avancé', Autonomie: '30h (ANC activé)', Recharge: 'USB-C, 3h recharge complète', Codec: 'LDAC, SBC, AAC', Micro: '8 microphones', Poids: '250g' },
    colors: ['#1a1a1a', '#c9b49a'],
  },
  {
    id: 4,
    name: 'MacBook Air M3 15" 8Go/256Go',
    brand: 'Apple',
    category: 'electronique',
    subcategory: 'laptops',
    price: 1299.00,
    originalPrice: 1299.00,
    discount: 0,
    rating: 4.8,
    reviews: 389,
    stock: 10,
    sold: 456,
    badge: 'new',
    isNew: true,
    isFeatured: true,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80&fit=crop',
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80&fit=crop',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=600&q=80&fit=crop',
    ],
    description: 'Le MacBook Air M3 15" est le laptop ultime pour la productivité et la création. Léger, puissant et avec une autonomie exceptionnelle.',
    specs: { Écran: '15.3" Liquid Retina 2560x1664', Processeur: 'Apple M3 8-Core', RAM: '8 Go unifiée', Stockage: '256 Go SSD', GPU: '10-Core GPU', Batterie: 'Jusqu\'à 18h', Ports: '2x Thunderbolt 4, MagSafe 3', Poids: '1.51 kg' },
    colors: ['#c0c0c0', '#4a4a4a', '#d4a483', '#e8e4e0'],
  },
  {
    id: 5,
    name: 'LG Side-by-Side 668L Réfrigérateur',
    brand: 'LG',
    category: 'electromenager',
    subcategory: 'refrigerateurs',
    price: 899.99,
    originalPrice: 1199.99,
    discount: 25,
    rating: 4.6,
    reviews: 156,
    stock: 5,
    sold: 203,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=600&q=80&fit=crop'],
    description: 'Le réfrigérateur LG Side-by-Side offre un espace généreux de 668L avec technologie InstaView et distributeur d\'eau intégré.',
    specs: { Capacité: '668 L (Frigo 441L + Congél 227L)', Classe: 'A++', Technologie: 'InstaView Door-in-Door', Couleur: 'Inox platinum', Dimensions: 'H 179x L 91.3x P 73.5 cm', Garantie: '2 ans', 'Niveau sonore': '39 dB', Connexion: 'Wi-Fi ThinQ' },
    colors: ['#c0c0c0', '#1a1a1a'],
  },
  {
    id: 6,
    name: 'Dyson V15 Detect Absolute Aspirateur',
    brand: 'Dyson',
    category: 'electromenager',
    subcategory: 'aspirateurs',
    price: 649.99,
    originalPrice: 749.99,
    discount: 13,
    rating: 4.8,
    reviews: 445,
    stock: 18,
    sold: 678,
    badge: 'popular',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop'],
    description: 'L\'aspirateur balai le plus avancé de Dyson. Laser détectant les particules invisibles et écran LCD affichant en temps réel la quantité de poussière aspirée.',
    specs: { Type: 'Aspirateur balai sans fil', Puissance: '240 AW', Autonomie: 'Jusqu\'à 60 min', Filtration: 'HEPA 5 couches', Capacité: '0.77 L', Poids: '3.1 kg', Technologie: 'Laser Detect', Niveaux: '3 modes d\'aspiration' },
    colors: ['#6366f1', '#f59e0b'],
  },
  {
    id: 7,
    name: 'Bose SoundLink Max Enceinte Portable',
    brand: 'Bose',
    category: 'audio',
    subcategory: 'enceintes',
    price: 379.99,
    originalPrice: 449.99,
    discount: 16,
    rating: 4.7,
    reviews: 298,
    stock: 30,
    sold: 512,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80&fit=crop'],
    description: 'L\'enceinte portable Bose SoundLink Max délivre un son puissant et immersif avec 20h d\'autonomie et une résistance IP67.',
    specs: { Autonomie: '20 heures', Résistance: 'IP67 (eau et poussière)', Bluetooth: '5.3', Recharge: 'USB-C', Dimensions: '23.6 x 9.8 x 9 cm', Poids: '1.17 kg', Couleurs: '3 coloris disponibles', Micro: 'Mains libres intégré' },
    colors: ['#1a1a1a', '#8B7355', '#d1fae5'],
  },
  {
    id: 8,
    name: 'Samsung Galaxy Tab S9 Ultra 12.4"',
    brand: 'Samsung',
    category: 'electronique',
    subcategory: 'tablettes',
    price: 1099.00,
    originalPrice: 1249.00,
    discount: 12,
    rating: 4.7,
    reviews: 178,
    stock: 12,
    sold: 267,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&q=80&fit=crop'],
    description: 'La tablette Android la plus puissante. Écran Dynamic AMOLED 2X de 12.4" avec S Pen inclus pour la productivité et la créativité.',
    specs: { Écran: '12.4" Dynamic AMOLED 2X', Résolution: '2960x1848', Processeur: 'Snapdragon 8 Gen 2', RAM: '12 Go', Stockage: '256 Go', S: 'Pen S Pen inclus', Batterie: '11200 mAh', OS: 'Android 13' },
    colors: ['#1a1a1a', '#E8E4E0'],
  },
  {
    id: 9,
    name: 'De\'Longhi ECAM650.85 Cafetière Auto',
    brand: "De'Longhi",
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 799.99,
    originalPrice: 999.99,
    discount: 20,
    rating: 4.6,
    reviews: 312,
    stock: 7,
    sold: 445,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80&fit=crop'],
    description: 'Machine à café automatique haut de gamme avec broyeur intégré, écran tactile couleur et système LatteCrema pour des cappuccinos parfaits.',
    specs: { Type: 'Machine expresso automatique', Pression: '19 bars', Capacité: '2L eau / 400g café', Broyeur: 'Grain intégré', Écran: 'Tactile couleur 3.5"', Chaleur: 'Double chauffe-eau', Programmes: '12 boissons', Garantie: '2 ans' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 10,
    name: 'Bosch WAX32M81FR Lave-linge 9kg',
    brand: 'Bosch',
    category: 'electromenager',
    subcategory: 'lave-linge',
    price: 549.99,
    originalPrice: 699.99,
    discount: 21,
    rating: 4.5,
    reviews: 234,
    stock: 6,
    sold: 389,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1626806787461-102c1a28f85a?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1626806787461-102c1a28f85a?w=600&q=80&fit=crop'],
    description: 'Lave-linge frontal Bosch Serie 8 avec moteur EcoSilence Drive, programme i-DOS et technologie ActiveWater Plus.',
    specs: { Capacité: '9 kg', Essorage: '1600 tr/min', Classe: 'A', Programmes: '28 programmes', Technologie: 'i-DOS + ActiveWater Plus', 'Niveau sonore': '48 dB', Connexion: 'Home Connect Wi-Fi', Garantie: '5 ans moteur' },
    colors: ['#ffffff', '#c0c0c0'],
  },
  {
    id: 11,
    name: 'Philips Hue White & Ambiante Kit',
    brand: 'Philips',
    category: 'smart-home',
    subcategory: 'eclairage',
    price: 129.99,
    originalPrice: 159.99,
    discount: 19,
    rating: 4.6,
    reviews: 543,
    stock: 45,
    sold: 1234,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1558618047-3c8a8b1a2b5e?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1558618047-3c8a8b1a2b5e?w=600&q=80&fit=crop'],
    description: 'Transformez votre intérieur avec l\'éclairage intelligent Philips Hue. Contrôlez 16 millions de couleurs depuis votre smartphone.',
    specs: { Contenu: '3 ampoules E27 + Pont Hue', Couleurs: '16 millions', Compatibilité: 'Alexa, Google Home, Apple HomeKit', Connexion: 'Zigbee via pont Hue', Durée: '25000 heures', Puissance: '9W équivalent 60W', Télécommande: 'App Hue', Protocole: 'Bluetooth + Zigbee' },
    colors: ['#ffffff', '#fbbf24', '#60a5fa', '#f472b6'],
  },
  {
    id: 12,
    name: 'Sony Alpha A7 IV Boîtier',
    brand: 'Sony',
    category: 'electronique',
    subcategory: 'cameras',
    price: 2499.00,
    originalPrice: 2799.00,
    discount: 11,
    rating: 4.9,
    reviews: 156,
    stock: 4,
    sold: 234,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80&fit=crop'],
    description: 'Hybride plein format polyvalent de Sony avec capteur BSI CMOS 33 MP, AF en temps réel et vidéo 4K 60p. Pour professionnels et passionnés.',
    specs: { Capteur: 'Full Frame BSI CMOS 33 MP', Processeur: 'BIONZ XR', AF: '759 points de détection de phase', Vidéo: '4K 60p, 4K 120p en recadrage', Stabilisation: '5 axes intégré', Écran: 'LCD tilting 3"', ISO: '50-204800 étendu', Tropicalisé: 'Oui (joints étanches)' },
    colors: ['#1a1a1a'],
  },
  {
    id: 13,
    name: 'Tefal ActiFry Genius XL Friteuse',
    brand: 'Tefal',
    category: 'cuisine',
    subcategory: 'friteuses',
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.5,
    reviews: 678,
    stock: 25,
    sold: 890,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1574269909862-7e1d70bb8078?w=600&q=80&fit=crop'],
    description: 'Friteuse à air chaud Tefal ActiFry Genius XL pour 1.7 kg de frites avec seulement une cuillère d\'huile. 9 programmes automatiques.',
    specs: { Capacité: '1.7 kg', Technologie: 'Air chaud + palette rotative', Programmes: '9 programmes auto', Puissance: '1550W', Cuve: 'Amovible et lavable lave-vaisselle', Huile: '1 cuillère à café', Dimensions: '36.6x30x27.4 cm', Garantie: '2 ans' },
    colors: ['#ffffff', '#1a1a1a'],
  },
  {
    id: 14,
    name: 'Xiaomi Robot Aspirateur S20+',
    brand: 'Xiaomi',
    category: 'electromenager',
    subcategory: 'aspirateurs',
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    rating: 4.4,
    reviews: 445,
    stock: 20,
    sold: 678,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1680279682703-26d384a35aec?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1680279682703-26d384a35aec?w=600&q=80&fit=crop'],
    description: 'Robot aspirateur intelligent avec navigation laser, puissance d\'aspiration 6000 Pa et station de vidange automatique.',
    specs: { Aspiration: '6000 Pa', Navigation: 'LDS Laser', Batterie: '5200 mAh (200 min)', Station: 'Vidange automatique 2.5L', Cartographie: 'Multi-niveaux', Hauteur: '9.65 cm (sous meubles)', App: 'Mi Home / Xiaomi Home', Filtration: 'HEPA' },
    colors: ['#ffffff', '#1a1a1a'],
  },
  {
    id: 15,
    name: 'Apple AirPods Pro 2e génération',
    brand: 'Apple',
    category: 'audio',
    subcategory: 'ecouteurs',
    price: 249.00,
    originalPrice: 279.00,
    discount: 11,
    rating: 4.8,
    reviews: 892,
    stock: 35,
    sold: 1567,
    badge: 'popular',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=600&q=80&fit=crop'],
    description: 'Les AirPods Pro 2 redéfinissent l\'audio avec une réduction active de bruit 2x plus efficace, l\'audio spatial adaptatif et la puce H2.',
    specs: { Puce: 'Apple H2', ANC: 'Réduction de bruit active 2x améliorée', Autonomie: '6h (ANC) + 24h boîtier', Recharge: 'Lightning / MagSafe / Qi2', Résistance: 'IPX4 (écouteurs + boîtier)', 'Audio Spatial': 'Adaptatif avec suivi de tête', Capteurs: 'Accéléromètre + gyroscope', Contrôle: 'Tactile + Force Sensor' },
    colors: ['#ffffff'],
  },
  {
    id: 16,
    name: 'KitchenAid Artisan Robot Pâtissier 4.8L',
    brand: 'KitchenAid',
    category: 'cuisine',
    subcategory: 'robots',
    price: 499.99,
    originalPrice: 599.99,
    discount: 17,
    rating: 4.8,
    reviews: 567,
    stock: 9,
    sold: 890,
    badge: 'popular',
    isNew: false,
    isFeatured: true,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1556910103-1c02745aae4d?w=600&q=80&fit=crop'],
    description: 'Le robot pâtissier iconique KitchenAid Artisan avec bol en acier inoxydable 4.8L, 10 vitesses et système d\'entraînement direct.',
    specs: { Capacité: '4.8 L', Puissance: '300W', Vitesses: '10 vitesses + impulsion', Accessoires: 'Fouet, crochet, feuille', Bol: 'Inox 4.8L', Système: 'Entraînement direct planétaire', Couleurs: '20+ coloris', Garantie: '5 ans' },
    colors: ['#ef4444', '#1a1a1a', '#c0c0c0', '#fbbf24', '#3b82f6'],
  },
  {
    id: 17,
    name: 'LG OLED Evo G3 55" 4K Dolby Vision',
    brand: 'LG',
    category: 'electronique',
    subcategory: 'televisions',
    price: 1599.99,
    originalPrice: 2199.99,
    discount: 27,
    rating: 4.9,
    reviews: 167,
    stock: 5,
    sold: 234,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1539293557942-03f892d14b7a?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1539293557942-03f892d14b7a?w=600&q=80&fit=crop'],
    description: 'L\'excellence OLED avec les panneaux EVO de LG pour des noirs absolus, des couleurs parfaites et un temps de réponse de 0.1ms.',
    specs: { Technologie: 'OLED EVO G3', Résolution: '4K Ultra HD', Taille: '55"', HDR: 'Dolby Vision IQ + HDR10 Pro', Fréquence: '120Hz', Processeur: 'α9 Gen 6 AI', 'Smart TV': 'webOS 23', Gaming: 'HDMI 2.1, FreeSync Premium Pro, G-Sync Compatible' },
    colors: ['#1a1a1a'],
  },
  {
    id: 18,
    name: 'Nespresso Vertuo Next Premium',
    brand: 'Nespresso',
    category: 'cuisine',
    subcategory: 'cafetières',
    price: 119.99,
    originalPrice: 169.99,
    discount: 29,
    rating: 4.5,
    reviews: 789,
    stock: 40,
    sold: 1234,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1606791405792-1004f1718d0c?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1606791405792-1004f1718d0c?w=600&q=80&fit=crop'],
    description: 'Machine Nespresso Vertuo avec technologie Centrifusion pour extraire le meilleur de chaque capsule. 5 tailles de café au programme.',
    specs: { Technologie: 'Centrifusion', Tailles: '5 (Espresso à Alto)', Capacité: '1.1 L', Chauffe: '30 secondes', Pression: '19 bars', Bac: '8 capsules usagées', Connexion: 'Bluetooth pour mises à jour', Couleur: 'Noir / Chromé' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 19,
    name: 'Samsung Galaxy Watch 6 Classic 47mm',
    brand: 'Samsung',
    category: 'accessoires',
    subcategory: 'montres',
    price: 349.99,
    originalPrice: 429.99,
    discount: 19,
    rating: 4.6,
    reviews: 345,
    stock: 20,
    sold: 567,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&fit=crop'],
    description: 'La Galaxy Watch 6 Classic avec lunette tournante physique, suivi santé avancé et autonomie de 40 heures.',
    specs: { Taille: '47mm', Écran: 'Super AMOLED 1.5" 480x480', OS: 'Wear OS 4 + One UI Watch 5', Processeur: 'Exynos W930', RAM: '2 Go', Stockage: '16 Go', Batterie: '425 mAh (40h)', Capteurs: 'ECG, BIA, SpO2, FC, Pression artérielle' },
    colors: ['#1a1a1a', '#c0c0c0'],
  },
  {
    id: 20,
    name: 'Vitamix 5200 Blender Professionnel',
    brand: 'Vitamix',
    category: 'cuisine',
    subcategory: 'blenders',
    price: 449.99,
    originalPrice: 549.99,
    discount: 18,
    rating: 4.9,
    reviews: 234,
    stock: 12,
    sold: 345,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&q=80&fit=crop'],
    description: 'Le blender professionnel Vitamix 5200 pour smoothies parfaits, soupes chaudes et bien plus. Moteur 2HP ultra-puissant.',
    specs: { Moteur: '2 HP (1.49 kW)', Vitesses: 'Variable 10 vitesses', Lames: 'Inox aiguisées laser 9cm', Bol: '2.1 L Tritan BPA Free', Chauffage: 'Friction (soupes chaudes)', Programmes: 'Manuel + 3 auto sur Pro', Garantie: '7 ans', Poids: '5.2 kg' },
    colors: ['#1a1a1a', '#ffffff', '#ef4444'],
  },
  {
    id: 21,
    name: 'Dell XPS 15 i7 32Go RTX 4070',
    brand: 'Dell',
    category: 'electronique',
    subcategory: 'laptops',
    price: 1899.99,
    originalPrice: 2299.99,
    discount: 17,
    rating: 4.7,
    reviews: 198,
    stock: 6,
    sold: 312,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&q=80&fit=crop'],
    description: 'Le Dell XPS 15 avec processeur Intel Core i7-13700H, GPU RTX 4070 et écran OLED 3.5K pour les créatifs et gamers exigeants.',
    specs: { Processeur: 'Intel Core i7-13700H', GPU: 'NVIDIA RTX 4070 8Go', RAM: '32 Go DDR5', Stockage: '1 To NVMe SSD', Écran: '15.6" OLED 3456x2160', Batterie: '86 Wh (13h)', Ports: '2x TB4, USB-A, SD, HDMI 2.1', Poids: '1.86 kg' },
    colors: ['#c0c0c0', '#1a1a1a'],
  },
  {
    id: 22,
    name: 'Anker PowerCore 26800 mAh',
    brand: 'Anker',
    category: 'accessoires',
    subcategory: 'chargeurs',
    price: 49.99,
    originalPrice: 69.99,
    discount: 29,
    rating: 4.7,
    reviews: 1234,
    stock: 60,
    sold: 3456,
    badge: 'popular',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=600&q=80&fit=crop'],
    description: 'Batterie externe ultra-capacité Anker 26800 mAh avec charge rapide PowerIQ et 3 ports USB pour recharger jusqu\'à 3 appareils simultanément.',
    specs: { Capacité: '26800 mAh', Sorties: '3x USB-A + 1x USB-C', Charge: 'PowerIQ 3.0 + USB-C 45W', Entrée: 'Micro USB + USB-C', Temps: '6.5h recharge complète', Poids: '490g', Certifications: 'CE, FCC, RoHS', Garantie: '18 mois' },
    colors: ['#1a1a1a', '#3b82f6'],
  },
  {
    id: 23,
    name: 'Philips 3000 Purificateur d\'Air',
    brand: 'Philips',
    category: 'smart-home',
    subcategory: 'purificateurs',
    price: 199.99,
    originalPrice: 279.99,
    discount: 29,
    rating: 4.5,
    reviews: 234,
    stock: 15,
    sold: 456,
    badge: 'new',
    isNew: true,
    isFeatured: false,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80&fit=crop'],
    description: 'Purificateur d\'air Philips Series 3000i avec filtre HEPA NanoProtect et capteurs intelligents pour une qualité de l\'air optimale.',
    specs: { Surface: 'Jusqu\'à 130 m²', Filtration: 'HEPA Grade H13 + Charbon actif', CADR: '333 m³/h', Capteurs: 'PM2.5, COV, Humidité, Température', Connectivité: 'Wi-Fi + App Clean Home+', Bruit: '19 dB (mode nuit)', Consommation: 'Max 60W', Garantie: '2 ans' },
    colors: ['#ffffff', '#3b82f6'],
  },
  {
    id: 24,
    name: 'GoPro HERO12 Black Action Camera',
    brand: 'GoPro',
    category: 'electronique',
    subcategory: 'cameras',
    price: 349.99,
    originalPrice: 449.99,
    discount: 22,
    rating: 4.7,
    reviews: 445,
    stock: 18,
    sold: 678,
    badge: 'promo',
    isNew: false,
    isFeatured: false,
    isPopular: true,
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=600&q=80&fit=crop'],
    description: 'La GoPro HERO12 Black capture des vidéos 5.3K ultra fluides avec stabilisation HyperSmooth 6.0 et une autonomie améliorée de 70%.',
    specs: { Vidéo: '5.3K 60fps / 4K 120fps', Photo: '27 MP', Stabilisation: 'HyperSmooth 6.0', Étanchéité: '10m sans boîtier', Batterie: '1720 mAh (+70% vs HERO11)', Écran: 'Avant 2.27" + Arrière 1.4"', HDR: 'Photo et vidéo HDR', Connexion: 'Wi-Fi + Bluetooth + GPS' },
    colors: ['#1a1a1a'],
  },
  {
    id: 25,
    name: 'Roborock S8 Pro Ultra Robot Aspirateur',
    brand: 'Roborock',
    category: 'electromenager',
    subcategory: 'aspirateurs',
    price: 1199.99,
    originalPrice: 1499.99,
    discount: 20,
    rating: 4.8,
    reviews: 178,
    stock: 8,
    sold: 234,
    badge: 'promo',
    isNew: false,
    isFeatured: true,
    isPopular: false,
    image: 'https://images.unsplash.com/photo-1701032267803-5534a6e0e3ef?w=600&q=80&fit=crop',
    images: ['https://images.unsplash.com/photo-1701032267803-5534a6e0e3ef?w=600&q=80&fit=crop'],
    description: 'Le robot aspirateur-laveur Roborock S8 Pro Ultra avec station tout-en-un : vidange automatique, remplissage d\'eau et lavage de la serpillière.',
    specs: { Aspiration: '6000 Pa', Navigation: 'LiDAR 3D + caméra RGB', Station: 'Vidange + Remplissage + Lavage serpillière', Brosse: 'DuoRoller Pro', Serpillière: 'Sonic Vibration 3000 vibr/min', Batterie: '5200 mAh (180 min)', App: 'Roborock / Alexa / Google', Filtre: 'HEPA E11' },
    colors: ['#1a1a1a', '#ffffff'],
  },
];

// Helper functions
function getProductById(id) {
  return PRODUCTS.find(p => p.id === parseInt(id));
}

function getProductsByCategory(cat) {
  if (!cat || cat === 'all') return PRODUCTS;
  return PRODUCTS.filter(p => p.category === cat);
}

function getFeaturedProducts() {
  return PRODUCTS.filter(p => p.isFeatured);
}

function getPopularProducts() {
  return PRODUCTS.filter(p => p.isPopular);
}

function getNewProducts() {
  return PRODUCTS.filter(p => p.isNew);
}

function getRelatedProducts(product, count = 4) {
  return PRODUCTS
    .filter(p => p.id !== product.id && p.category === product.category)
    .slice(0, count);
}

function filterProducts(filters = {}) {
  let result = [...PRODUCTS];

  if (filters.category && filters.category !== 'all') {
    result = result.filter(p => p.category === filters.category);
  }
  if (filters.brands && filters.brands.length > 0) {
    result = result.filter(p => filters.brands.includes(p.brand));
  }
  if (filters.minPrice !== undefined) {
    result = result.filter(p => p.price >= filters.minPrice);
  }
  if (filters.maxPrice !== undefined) {
    result = result.filter(p => p.price <= filters.maxPrice);
  }
  if (filters.minRating !== undefined) {
    result = result.filter(p => p.rating >= filters.minRating);
  }
  if (filters.badge) {
    result = result.filter(p => p.badge === filters.badge);
  }
  if (filters.inStock) {
    result = result.filter(p => p.stock > 0);
  }
  if (filters.search) {
    const q = filters.search.toLowerCase();
    result = result.filter(p =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
    );
  }

  // Sort
  switch (filters.sort) {
    case 'price-asc': result.sort((a, b) => a.price - b.price); break;
    case 'price-desc': result.sort((a, b) => b.price - a.price); break;
    case 'rating': result.sort((a, b) => b.rating - a.rating); break;
    case 'popular': result.sort((a, b) => b.sold - a.sold); break;
    case 'new': result.sort((a, b) => (b.isNew ? 1 : 0) - (a.isNew ? 1 : 0)); break;
    default: break;
  }

  return result;
}

function formatPrice(price) {
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(price);
}

function renderStars(rating) {
  const full = Math.floor(rating);
  const half = rating % 1 >= 0.5;
  let html = '';
  for (let i = 1; i <= 5; i++) {
    if (i <= full) html += '★';
    else if (i === full + 1 && half) html += '⯨';
    else html += '☆';
  }
  return html;
}
